### ISSUE TITLE
Invalid terrain "curious_structure_b2" in overmap special "Curious Structure" and others

### ISSUE THREAD

**Issue by Hellcommander** [chaosvolt/cdda-arcana-mod#1]
Invalid terrain "curious_structure_b2" in overmap special "Curious Structure" and others I've been trying to find what is the error but only debug for it is 
Function: void overmap_special::check() const
file : src/overmap,cpp
line:986

**Comment by chaosvolt** [comment]
Is this occurring in the compiled game's version too, or just mine?

**Comment by Hellcommander** [comment]
happens in mine too mines the latest dev build


-----Original Message-----

**Comment by chaosvolt** [comment]
I'm currently testing this in the latest build at present, 5938. The version in the game seems to not generate any errors on starting or loading a game, nor on approaching curious structures, and can enter the bottom level without issue.

Testing after replacing the base game's version with the one from this repo, same deal. Anything else that might be causing this? Are you getting an inexplicable load error, or is it a "can't find starting location" error when trying to start Seeker of the Arcane?

**Comment by Hellcommander** [comment]
Ill test it later after i update an older mod to newest expermental.

**Comment by chaosvolt** [comment]
Right now I'm further testing claims by @mugling about copy-from breakage. I suspect he's talking shit to shut down someone else's attempt to fix my mod in the main game.

**Comment by Hellcommander** [comment]
Seems latest patchs fixed the error.

**Comment by chaosvolt** [comment]
I would assume it was a mapgen error in between the last builds I had on hand and the most recent one I tested. Guess it can be closed for now.

**Comment by Hellcommander** [comment]
nm seems i still have the error when creating a world

**Comment by Hellcommander** [comment]
only errors im getting is the stuff able invalid terrain

**Comment by Hellcommander** [comment]
about

**Comment by Hellcommander** [comment]
seems game forgot the arcana selection no error if its only arcana

**Comment by chaosvolt** [comment]
That's odd. Are you replacing their version of Arcana with this repo? Because they obsoleted it now. ._.

**Comment by Hellcommander** [comment]
Not having any issues so far atm with your mod though though i'm using your updated version (i heard copy from might be broken in current expermental and one of mods before that used it I've used (cataysm++) had some broken scenarios before because these one modified base game sceneries with copy-from. 


-----Original Message-----

**Comment by Hellcommander** [comment]
yup deleting and replacing :P it just forgot the checked off mod before.


-----Original Message-----

**Comment by chaosvolt** [comment]
Guess that means it can be closed if there are no further problems. I'll have to keep an eye on copy-from for now, in case it breaks.

**Comment by chaosvolt** [comment]
Closing for now, poke me if something of this nature recurs.
