### ISSUE TITLE
Invalid flad blocks world

### ISSUE THREAD

**Issue by Alterforce** [chaosvolt/cdda-arcana-mod#105]
When making a world with the arcana mod in build 9990, the world cannot be played due to the flag 'REGENERATES_1
![arcana monster error](https://user-images.githubusercontent.com/43394039/70683801-b6001e80-1cde-11ea-986d-da956f2d374f.png)
'

**Comment by chaosvolt** [comment]
Update arcana, that was already fixed. See commit: https://github.com/chaosvolt/cdda-arcana-mod/commit/c0e0593ffa0c8f62e5f913c577fcced8c9b48176
