### ISSUE TITLE
Suggestion: Allow Woven Seal: Healing to mend broken bones

### ISSUE THREAD

**Issue by vlad1492** [chaosvolt/cdda-arcana-mod#112]
It takes an ingredient from a Skeletal Juggernaut, seems a worthy foe for it.

**Comment by chaosvolt** [comment]
I'd have to pester @korggent to add some way to force mending via magic to the code, there's no way to do that via JSON at present. I've tried shenanigans like effects that block the "disabled limb" effect, doesn't seem to work.

I might see if it's possible to hack around it via forcing a given duration of "mending limb" will force it to set even without a splint, but I doubt it.

Side note, a couple other monsters can drop twisted bones too, though most are also fairly tough and/or rare. Skeletal juggernauts are just notable for potentially dropping any of the bone-like monsterparts. :3

**Comment by chaosvolt** [comment]
So, I attempted a whole range of JSON hacks to try and make this work, including having the spell equip you with a fake splint. It seems that, no matter what you do, you can't force the mending effect even if you're actually wearing a proper splint in the first place. So in the absence of any C++ additions, I'm afraid this is out of my reach. :/
