### ISSUE TITLE
Arcana - Wyrmskin Armor should be 'Very Fancy' 

### ISSUE THREAD

**Issue by vlad1492** [chaosvolt/cdda-arcana-mod#115]
Is your feature request related to a problem? Please describe.

Wyrmskin armor is described as 'well decorated' but has no 'Fancy' oir 'Very Fancy' attribute.
Describe the solution you'd like

Make it very fancy
Describe alternatives you've considered

Forget the coveted brand-name wyrmskin and just wear dingy grey worm-skin like a drudge.

**Comment by chaosvolt** [comment]
I guess that'd work, or I could reword the description. That said, most armor in the mod would count as fairly ornate. Gilded aegis has feathery golden scales, mantle of shadows has a somewhat decorative fur trim (or feathers as an alternative in the recipe), etc.

**Comment by vlad1492** [comment]
Aw yeah, bring on the bling. 
Stylish survivors deserve this.

**Comment by chaosvolt** [comment]
Guess it'd work for at least a couple more items, true. Gilded aegis and wyrmskin armor at least, though maybe not the mantle of shadows. :3

**Comment by vlad1492** [comment]
Jade hauberk incorporates an aegis too
