### ISSUE TITLE
Build 10403 error

### ISSUE THREAD

**Issue by Deuteriumd2o** [chaosvolt/cdda-arcana-mod#118]
I get this error when loading or creating new game since updating to 10403:

src/main_menu.cpp:1072 [bool main_menu::load_character_tab(bool)] Error: data/mods//Arcana/monsters.json: line 550:5: missing mandatory member "spell_data"

        "monster_message": "Oppressive heat radiates from the spirit of fire."
      }
    ]
    ^
     ,
    "death_drops": "mon_spirit_of_fire_death_drops",
    "death_function": [ "MELT" ],

I'll keep playing 10402 untill it is resolved. Thanks for this great mod, by the way!

**Comment by chaosvolt** [comment]
Update Arcana, reminder that when you hit "update everything" on the launcher, it does NOT actually update everything, third-party mods have to be updated by deleting and re-obtaining them from the mods tab.

Relevant change was https://github.com/CleverRaven/Cataclysm-DDA/pull/38585, https://github.com/chaosvolt/cdda-arcana-mod/pull/117 was merged about an hour afterward.
