### ISSUE TITLE
Error prevents world from loading

### ISSUE THREAD

**Issue by Haranador** [chaosvolt/cdda-arcana-mod#121]
CDDA Build 10416
Arcana: Latest commit 94141d8
Mods: Acana only

Error message:
https://i.imgur.com/U1K0hL2.png

**Comment by chaosvolt** [comment]
Update arcana, launcher does not update third-party mods for you.

**Comment by Haranador** [comment]
Ok, I did overwrite the old version before writing the report. Deleting Arcana and installing the new version works.

**Comment by chaosvolt** [comment]
Issue is basically that the "update everything" button only touches the build, not third-party mods, so the process to update your mods is non-intuitive. I really need to create a label for these launcher-induced false positive issues so I can track just how many times this has come up...
