### ISSUE TITLE
Pattern Scrolls Are People!

### ISSUE THREAD

**Issue by CptCodpiece** [chaosvolt/cdda-arcana-mod#123]
![image](https://user-images.githubusercontent.com/47262327/77404098-98376080-6d87-11ea-8079-06c68df8addb.png)

Used a healing pattern scroll and got a cannibalism malus to morale. I think it may be confusing pattern scrolls for mutated human leg/arms/fetuses.

**Comment by chaosvolt** [comment]
That's...oh, I'm guessing it's transferring flags due to a potential ingredient having the cannibal flag, seems I need to make more use of `NO_CRAFT_INHERIT`. This is only even an issue because of bugs that make it so that single-use magic items are best implemented as consumables.

**Comment by chaosvolt** [comment]
Okay, fuck. I've applied `NO_CRAFT_INHERIT` all over the place and it seems to be broken. :/

**Comment by chaosvolt** [comment]
![image](https://user-images.githubusercontent.com/11582235/77462236-d9ecf900-6dd1-11ea-9596-e08ba38e0e81.png)

**Comment by chaosvolt** [comment]
Okay, I can now confirm that `NO_CRAFT_INHERIT` is just entirely bugged, go report this in the proper place as this is a CDDA bug: https://github.com/CleverRaven/Cataclysm-DDA/issues
