### ISSUE TITLE
Hermit weapon type problem

### ISSUE THREAD

**Issue by Meridian117** [chaosvolt/cdda-arcana-mod#124]
DEBUG    : Error: item group "NC_HERMIT_weapon" already defined with type "collection"

 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 781

**Comment by chaosvolt** [comment]
Are you using the master branch of Arcana with 0.D stable? If you're using 0.D stable, use the release for it found here: https://github.com/chaosvolt/cdda-arcana-mod/releases

**Comment by Meridian117** [comment]
I'm running experimental, should have said that at the start

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by chaosvolt** [comment]
Then make sure that both the build and mod are up to date, as that error indicates something there is out of sync (as a while back that itemgroup was changed from a collection to a distribution).

**Comment by Meridian117** [comment]
Understood. I updated the base game today, then added in arcana after that. I'll try re-updating core

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by chaosvolt** [comment]
Alright, tell me if anything changes.

**Comment by Meridian117** [comment]
I fixed it.  I just had to delete the folder and then re-install arcana.  I think because I keep just copy-pasting the new versions as they come out, it must have doubled up on something.  We're all clear now :)
