### ISSUE TITLE
Urban Awakening scenario can't generate the starting area

### ISSUE THREAD

**Issue by mding9** [chaosvolt/cdda-arcana-mod#127]
Whenever I try starting a game in urban awakening, the game says "Unable to find valid starting location. Please report this error". Are urban magic areas not generating?

**Comment by chaosvolt** [comment]
Shit, can confirm this is indeed happening. I'll need to check to see if regional overlays have been fucked with.

**Comment by chaosvolt** [comment]
After some tinkering around I suspect that it's not regional overlays. but instead they've converted most houses to match up with a specific pre-defined basement. So I'll need to define a new house variant to match these basements...

**Comment by chaosvolt** [comment]
Okay, further testing has left me increasingly suspecting that regional overlays are just plain outright fucked. :/
