### ISSUE TITLE
Martial Arts Object Crash

### ISSUE THREAD

**Issue by hitmancho** [chaosvolt/cdda-arcana-mod#129]
Running Build #10481 with the latest commits and I am getting this when loading my save:

DEBUG    : Error: data/mods//Arcana/martialarts.json: line 89:27: tried to start object, but found '[', not '{'

        "max_stacks": 1,
        "bonus_dodges": 2,
        "flat_bonuses": [ [
                          ^
                            "dodge", 1.0 ] ]
      },
      {

 FUNCTION : bool main_menu::load_character_tab(bool)
 FILE     : src/main_menu.cpp
 LINE     : 1099

Did they change how martial art bonuses should be defined?

**Comment by chaosvolt** [comment]
That's...odd. Is those pre or post 0.E stable?

**Comment by hitmancho** [comment]
Post 0.E stable, latest experimental build (10481).

**Comment by chaosvolt** [comment]
Shit. Will look into it in a moment, I was still trying to fix a different bug that cropped up. @.@
