### ISSUE TITLE
Gunmods can now add ammo_effects to weapons 

### ISSUE THREAD

**Issue by John-Candlebury** [chaosvolt/cdda-arcana-mod#13]
I thought you could be interested in knowing this, since you can use it to create enchanted bows and guns. A few examples of how this works are in laser_gunmods.json

Also good to know you are still working on this mod, it has several fun ideas.

**Comment by chaosvolt** [comment]
Hmm? Interesting. Dunno what I could do with it just yet. Logical answer would be fire arrows maybe, but there's a lot of flame weapons in the mod already. Plus those might have to be rare and/or hard to craft, as there'd be no way to make it additionally consume any sort of essence.

Could pester @Alasnuyo though, I recently found their addon mod that looks interesting. I'm not yet sure about mainlining any of their additions, but 2 ideas interest me:
* The general idea of arcana-based martial arts. Exact way they use it I'm unsure about, I'd want to see whether they fit the theme of the in-lore factions maybe.
* Magitek ideas. I dunno about adding the stuff in it, but what I've been thinking about is adding an optional lab mapgen, they could use it as a source of extra itemgroups to add magitek to.

**Comment by chaosvolt** [comment]
Closing for now, dunno what to do with this at present. When https://github.com/CleverRaven/Cataclysm-DDA/pull/21555 is merged I got a neat idea though.
