### ISSUE TITLE
Game quits to main menu when i try to create a new character preventing me to start a new game

### ISSUE THREAD

**Issue by 3NC3PH4L0ND1V3** [chaosvolt/cdda-arcana-mod#131]
Loaded only DDA core and your mod to ensure there is no other mod conflict.

 DEBUG    : Error: data/mods//Arcana/chargen/start_locations.json: line 3:30: must specify either id or abstract

[
  {
    "type": "start_location",
                             ^
    "ident": "strange_grove",
    "name": "Strange Grove",
    "target": "strange_grove",

 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 902

Hope you can fix this soon since your mod is awesome!

**Comment by chaosvolt** [comment]
There we go. Bit sad they had to change the fields used, they could've retained `ident` and `target` to not break stuff, but... :/
