### ISSUE TITLE
Failing to load in current build (10501)

### ISSUE THREAD

**Issue by lapis413** [chaosvolt/cdda-arcana-mod#133]
with the current build, the game fails to load a world with the following error 

DEBUG    : Error: data/mods//Arcana/chargen/start_locations.json: line 3:30: must specify either id or abstract

[
  {
    "type": "start_location",
                             ^
    "ident": "strange_grove",
    "name": "Strange Grove",
    "target": "strange_grove",

 FUNCTION : bool main_menu::load_character_tab(bool)
 FILE     : src/main_menu.cpp
 LINE     : 1099

**Comment by lapis413** [comment]
sorry, i just realized this was posted and fixed yesterday, i'm just down a version. unsure how to delete this

**Comment by chaosvolt** [comment]
Let me guess, using the launcher? Reminder that "update game" does not affect third-party mods.
