### ISSUE TITLE
Character Creation Error (Boot to Title)

### ISSUE THREAD

**Issue by BloodCri** [chaosvolt/cdda-arcana-mod#135]
I've been getting errors in stable with the stable version, the most recent updated version with the most recent updated CDDA and both using and not using the launcher. All errors start with a series of these messages:

 DEBUG    : couldn't parse color: c_light_grey

 FUNCTION : color_id color_manager::name_to_id(const string&) const
 FILE     : src/color.cpp
 LINE     : 103

 DEBUG    : couldn't parse color: c_light_grey

 FUNCTION : color_id color_manager::name_to_id(const string&) const
 FILE     : src/color.cpp
 LINE     : 103

 
And both the launcher and non-launcher version end with this error followed by being booted to title:

DEBUG    : Error: data/mods//Arcana/monsters.json: line 477:7: invalid monster flag: "REGENERATES_1"

    "death_function": [ "MELT" ],
    "flags": [
      "
      ^
       REGENERATES_1",
      "NOHEAD",
      "HARDTOSHOOT",

 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 820

**Comment by chaosvolt** [comment]
Make sure you're using the correct stable. The 0.D releases are for 0.D stable, the 0.E release is for 0.E stable. My guess for the looks of it is you're using one of the 0.D stable releases with 0.E stable.
