### ISSUE TITLE
Pattern Scrolls Dont Level Up Spells

### ISSUE THREAD

**Issue by LordPancitoFresco** [chaosvolt/cdda-arcana-mod#139]
I Started Playing this save on 0.E but had move into experimentals. Just like the title says the pattern scrolls i just crafted dont level up my spells, Im currently on experimental build #10604
![ccddaarcanabug](https://user-images.githubusercontent.com/64502015/80748324-1dd2cc80-8afb-11ea-8fa3-246e0b8eb840.png)

As you can see in the image i used 6 pattern scrolls of Confuse Monster but it is still at level 1, i tried with other pattern scrolls but the ones i tried (blood clarity pattern scroll) dont work either.
This happening may actually be something intended and its just me that doesnt know, but i dont think so since it used to work.

I havent done a lot of reports before but on the other one i did they asked for this info so im putting it in just in case
- OS: Windows 8.1
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.E-1368-g2880e7d [32-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    C.R.I.T Expansion Mod [crt_expansion],
    Arcana and Magic Items [Arcana],
    Magiclysm [magiclysm],
    DinoMod [DinoMod]
]

**Comment by chaosvolt** [comment]
Well that's...not good. They broke that feature? :/

**Comment by chaosvolt** [comment]
Okay, I just tested it. Pattern scrolls indeed don't work. But, the free level-ups for preceding spells from the restored ritual blade DO work,

![image](https://user-images.githubusercontent.com/11582235/80777135-cdbf2e80-8b29-11ea-9b83-4392c49fbc6b.png)

This means that I have a workaround, at least.

**Comment by chaosvolt** [comment]
There we go, that should do it, unless the code changes again...
