### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by RavengerMan** [chaosvolt/cdda-arcana-mod#142]
When i am creating a world and i have arcana and magic in my mods list when it load the mods my game crash when i remove it doesn't crash i am on android

**Comment by chaosvolt** [comment]
What's the load error? This doesn't tell me anything. :/

**Comment by chaosvolt** [comment]
I can't test android builds specifically, but at present I'm not having any JSON errors in the build I'm able to test. Make certain you're matching either:
1. The latest available experimental build of CDDA with the current master branch of Arcana (see main page, hit "clone or download" button).
2. 0.D or 0.E stable builds of CDDA with the proper release of Arcana (see releases section from main page).

And tell me if anything acts up after doing so.
