### ISSUE TITLE
Feature request: Arcane recipes should have their own (sub)category

### ISSUE THREAD

**Issue by Torbenbeta** [chaosvolt/cdda-arcana-mod#146]
**Description**
Arcane recipes are difficult to find, if not sought via search for skill:arcane, which is a bit tedious

**Suggestion**
Analogous to the magicalysm mod, add either a proper category (enchanted in magicalysm) or subcategories arcane in the crafting menus.
So I would find the essences in other -- arcane for example. This would ease finding of arcane recipes.

**Comment by chaosvolt** [comment]
Hmm. I've been tempted to do that before, and it might help players find the recipes that way, true.

**Comment by chaosvolt** [comment]
![image](https://user-images.githubusercontent.com/11582235/88330905-bee3b480-ccf1-11ea-9b10-35e8bcfa81cf.png)

How's this look for organization? Has weapons, ammo (essences will be there), alchemical recipes (might shift silver and gold making there?), armor (including wearable tools and the two wearable trophy items), pattern scrolls (also includes magic seals), and misc.
