### ISSUE TITLE
Invalid enum string on load

### ISSUE THREAD

**Issue by grimmspector** [chaosvolt/cdda-arcana-mod#150]
Working with 0.E+10915, on load get:
`13:30:41.076 ERROR : src/main_menu.cpp:1146 [bool main_menu::load_character_tab(bool)] Error: Invalid enum string 'fire' for '11damage_type'`

Fatal error stops the mod from being loaded.

**Comment by chaosvolt** [comment]
Ah, that would be the change to fire and bio damage types as specified in spells, one sec. Was gonna take care of that once I got back home, so give me a bit. ^^"
