### ISSUE TITLE
Experimental 10927 Undefined Item

### ISSUE THREAD

**Issue by grimmspector** [chaosvolt/cdda-arcana-mod#151]
Had an air talisman in my inventory, and when I updated the game to this version it became undefined and I get an Undefined error for Arcana during load. No clue what other Arcana items may be affected.

**Comment by chaosvolt** [comment]
Odd. Maybe sure you didn't update to an old release, though I'm fairly certain the 0.D release should be the only one old enough to predate the addition of air talismans...

**Comment by chaosvolt** [comment]
Having trouble reproducing this. I set up a character on 10923, spawned in an air talisman, then moved the save over to 10927. Tested both loading that character in to find they still had it, and tested the new game menu for any load errors too.

**Comment by grimmspector** [comment]
> Having trouble reproducing this. I set up a character on 10923, spawned in an air talisman, then moved the save over to 10927. Tested both loading that character in to find they still had it, and tested the new game menu for any load errors too.

Quite sure, and Arcana is in my /mod not /data/mod directory, so it doesn't auto update or get deleted, etc.
I can provide some screens or logs.

Here's the debug:
`10:13:26.342 ERROR : src/game.cpp:3076 [bool game::load_packs(const string&, const std::vector<string_id<MOD_INFORMATION> >&, loading_ui&)] unknown content Arcana`

Here's an image of the item spawn menu showing the issue [https://imgur.com/a/FBUhzFk](https://imgur.com/a/FBUhzFk)

**Comment by chaosvolt** [comment]
It's saying that it can't find Arcana mod when trying to load the save. I actually encountered that during testing because at first I moved my config and save folders to 10927, but forgot to put arcana in that build. Testing a second time after putting arcana in where it belongs got it loading right.

**Comment by grimmspector** [comment]
> It's saying that it can't find Arcana mod when trying to load the save. I actually encountered that during testing because at first I moved my config and save folders to 10927, but forgot to put arcana in that build. Testing a second time after putting arcana in where it belongs got it loading right.

Interesting, it was there, but maybe something else was missing. I reinstalled Arcana and that did indeed fix the error. Thanks!
