### ISSUE TITLE
Cursed blade doesn't spawn in the floating temple

### ISSUE THREAD

**Issue by TheAnay256** [chaosvolt/cdda-arcana-mod#152]
Instead of a back scabbard containing a cursed blade, only an empty back scabbard spawns in the final room.

Edit: tried changing` { "item": "stormbringer", "container-item": "bscabbard" }` to `{ "item": "bscabbard", "contents-item": "stormbringer" }` in item_groups_chalice.json to follow the pattern established when zombie soldiers drop a sheath with a combat knife, but no dice.

**Comment by chaosvolt** [comment]
Hmm, strange. If I have to I can simply spawn the two items separately, lore-wise the person who hid with it probably had a "fall on their sword" moment on realizing they were trapped in the temple with the host of the archon and not able to escape, so it being sheathed wouldn't make too much sense anyway. :/
