### ISSUE TITLE
Avitar error thrown

### ISSUE THREAD

**Issue by meelock** [chaosvolt/cdda-arcana-mod#156]
DEBUG    : constraint for event_transformation avatar_arcana_location_curious_structure matches constant curious_structure of type oter_id but that is not a valid value of that type

 FUNCTION : void value_constraint::check(const string&, cata_variant_type) const
 FILE     : src/event_statistics.cpp
 LINE     : 227

Mods included: Aftershock, arcana, blaze industries, crit, magiclysm, mst extra, cdda++, mma, udp tiles, dorf life.

**Comment by chaosvolt** [comment]
Tested in latest build and yep, getting this on load, trying to figure out what's new that might've caused it...

**Comment by chaosvolt** [comment]
Turned out to be the event stuff in obsolete.json being incorrect in format. Since it was dumped in that file due to never working right anyway, there shouldn't be any old saves out there that'd actually be affected by deleting it. That fixed it.
