### ISSUE TITLE
Chinese Translation

### ISSUE THREAD

**Issue by linonetwo** [chaosvolt/cdda-arcana-mod#157]
How can I help? Is it easy to support it?

**Comment by chaosvolt** [comment]
I'm afraid that I'm not certain how translations work, nor any easy way to set them up. CDDA itself is capable of setting up localization, but I'm unsure if there's any way to use that for third-party mods, or if the only method is to make a full copy of the mod's JSON files with all relevant text translated.

**Comment by linonetwo** [comment]
Can I do it use the method described in https://github.com/CleverRaven/Cataclysm-DDA/blob/d26d54bfdd1b634687c6a5a8c9a0103040dd7c30/doc/TRANSLATING.md ?

**Comment by linonetwo** [comment]
Seems there is a way https://github.com/CleverRaven/Cataclysm-DDA/issues/29077

we can use "copy from" to create new object that only replace the string, but it will be difficult to maintain.

**Comment by chaosvolt** [comment]
Hmm. Looking at it, it might indeed be possible but I'd likely need help with translations, and I don't know how all that quite functions. It looks like the proposed solution in that issue is nothing more than a way to streamline the less-than-ideal solution of creating a complete copy of the JSON with all the strings translated, which is still not exactly ideal. :/

**Comment by linonetwo** [comment]
They said I can do this:

Extract mod strings using existing scripts, translate them, add translated strings to po files and compile updated files to mo. 

For detail: Create your own Transifex project for mod, use Python script for strings extraction on mod folder, upload that as a file to your project, then just get translated results and merge them with the right language file.

As https://github.com/CleverRaven/Cataclysm-DDA/issues/25566

---

Actually, most people in China are still playing 0.D and 0.E stable, so they use the translated version of your Arcana out of the box, but I'm playing the latest experimental, so I want to do something. I don't quite understand what po and mo are, but I will try to. (But it would be better if you set all this up, so I can just start translating...)

**Comment by chaosvolt** [comment]
Ah, that's..I've actually had some issues running python scripts last several times I've tried, to be honest. :/

And same, I'm really not familiar with those files either.

**Comment by linonetwo** [comment]
I got some idea, I will look into it this weekend, but may need you to register a Transifex account and create a translation project for arcana first.

**Comment by chaosvolt** [comment]
Ah, I'll have to look into it, been kinda not as active with modding in general lately. @.@

**Comment by linonetwo** [comment]
Me too, this is normal, (I'm not active on my other opensource projects too, because I'm playing CDDA ...)

**Comment by chaosvolt** [comment]
In my case I haven't been playing as much CDDA either. I'll go ahead and leave this open for now but no idea when I'll have the chance to tinker with this, nor if I'd even make much progress on trying.

**Comment by linonetwo** [comment]
Hi chaosvolt, I made a translated version, using my custom translate script.

https://github.com/linonetwo/cdda-arcana-mod-chinese

I will try to keep it update, I will merge your latest master and rerun the translation script every time you have a release!

**Comment by chaosvolt** [comment]
Ah, alright. Sorry for the difficulties I've had with this.

**Comment by linonetwo** [comment]
Your mod is great, I think the difficulty comes from the CDDA's code structure, it don't allow a "patch mod" like https://steamcommunity.com/sharedfiles/filedetails/?id=754350883 which is a separate mod just patch every string that needs translation.

Anyway, with my translation script, it will be very easy now, thank you for making this mod.
