### ISSUE TITLE
Mark: Revenant Blood from Dragonblood mutation tree bugged on experimental

### ISSUE THREAD

**Issue by Kosolaper** [chaosvolt/cdda-arcana-mod#159]
It seems this spell do not protect from poison and food poison.
How to reproduce:
1) Activate spell
2) Drink from toilet/chunk of water several times
3) Get poisoned and food poisoned
Expected behavior:
Do not getting listed debuffs.

**Comment by chaosvolt** [comment]
Huh. Just tested it and it does indeed seem to be acting up.

Ah, found the cause of it. At some point when converting some effects, I entered `remove_effects` instead of `removes_effects`.
