### ISSUE TITLE
Some kinda Error

### ISSUE THREAD

**Issue by SirClarke** [chaosvolt/cdda-arcana-mod#160]
Not sure if it's on my end or not but this is it 
![Screenshot (4)](https://user-images.githubusercontent.com/31796878/95669576-58cc3800-0b50-11eb-9303-6ddb6370d2db.png)

**Comment by chaosvolt** [comment]
Update Arcana, reminder the launcher does not update mods for you, and reminder to actually delete the old folder before you update manually, or else you may miss removed files like obsolete.json.

This was fixed two days ago: https://github.com/chaosvolt/cdda-arcana-mod/commit/440dc6a679cb73e631dc3c38b369d508ea1ad87f

Please tell me however if any load error ensues from removing obsolete.json afterward, if you're using an old save. The contents of obolsete.json should've been old enough by now that it was safe to get rid of it, but you never know for sure.

**Comment by SirClarke** [comment]
oh ok thanks a lot sadly I deleted the old save
