### ISSUE TITLE
Error preventing world from loading

### ISSUE THREAD

**Issue by Enderlordalatreon** [chaosvolt/cdda-arcana-mod#161]
Not sure how to describe this error sadly, so I'll just post it.

 DEBUG    : Error: Json error: data/mods//Arcana/obsolete.json:233:28: missing mandatory member "shape"

    "flags": [ "SOMATIC", "NO_HANDS", "NO_FAIL" ],
    "extra_effects": [ { "id": "arcana_aftermath_suppression_buff", "hit_self": true, "max_level": 5 } ],
    "effect": "spawn_item",
                           ^
    "effect_str": "halo_dampening",
    "energy_source": "HP",
    "difficulty": 20,

 FUNCTION : bool main_menu::load_character_tab(bool)
 FILE     : src/main_menu.cpp
 LINE     : 1146

I'm on the latest CDDA version as well as the latest Arcana version, as in the one uploaded 3 hours ago. Thanks.

**Comment by chaosvolt** [comment]
Delete obsolete.json and it should work. You most likely copied the new arcana folder directly into the old one, hence why obsolete.sjon didn't get removed when you updated after https://github.com/chaosvolt/cdda-arcana-mod/commit/440dc6a679cb73e631dc3c38b369d508ea1ad87f

See also, issue: https://github.com/chaosvolt/cdda-arcana-mod/issues/160

**Comment by Enderlordalatreon** [comment]
Ack, that was it. Sorry about that.
