### ISSUE TITLE
Cursed Blade does not fit back scabbard

### ISSUE THREAD

**Issue by lordmatiz** [chaosvolt/cdda-arcana-mod#163]
Just like the title - cursed blade (3,25L; 1,8m) vs back scabbard (3,75L. 1,4m). 
It's just my guess, but after finding them next to each other in temple - they should be compatible.

![image](https://user-images.githubusercontent.com/16430038/96855769-7b6a2500-145d-11eb-9e0f-a93cbf744132.png)

and back scabbard
![image](https://user-images.githubusercontent.com/16430038/96855694-61c8dd80-145d-11eb-81d3-fd543a67200d.png)

**Comment by chaosvolt** [comment]
I've been needing to implement item lengths for stuff that no longer relies on copy-from, yeah. Will tackle this in a bit.

**Comment by chaosvolt** [comment]
Discovery of the day: back scabbard cannot hold a zweihander.
