### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Nukiho** [chaosvolt/cdda-arcana-mod#165]
DEBUG    : Error: Json error: data/mods//Arcana/obsolete.json:233:28: missing mandatory member "shape"

    "flags": [ "SOMATIC", "NO_HANDS", "NO_FAIL" ],
    "extra_effects": [ { "id": "arcana_aftermath_suppression_buff", "hit_self": true, "max_level": 5 } ],
    "effect": "spawn_item",
                           ^
    "effect_str": "halo_dampening",
    "energy_source": "HP",
    "difficulty": 20,

 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 861

**Comment by chaosvolt** [comment]
Delete obsolete.json. This is why it's better to delete the old folder and replace with the new one when updating, not just dumping the new folder into the old one.
