### ISSUE TITLE
Summoned Infinity Centipedes

### ISSUE THREAD

**Issue by Roet718** [chaosvolt/cdda-arcana-mod#166]
I've noticed that summoned giant centipedes eventually evolve into Infinity centipedes, i dont really understand under what conditions it happens but, its pretty cool. What's less cool though is that they seem to be pacifist and will never attack anything even if its killing them. Also they will follow at your heels like lost puppies, which is endearing until they shove your vehicle around you damaging your vehicle and crushing you.

**Comment by chaosvolt** [comment]
What in the flying...oh. It's a consequence of the new monster evolutions, isn't it? One sec I guess.

**Comment by chaosvolt** [comment]
Should be fixed by https://github.com/chaosvolt/cdda-arcana-mod/commit/06ae9ac39f08632b96258669a7357a0c2f4832a8 and https://github.com/chaosvolt/cdda-arcana-mod/commit/9048429178b5aebe6b15c4803261e056e9ba66a1

**Comment by Roet718** [comment]
Ah man, i was hoping that was at least partially intentional. Nice fix though thanks a bunch!

**Comment by chaosvolt** [comment]
And here when I read the title I assumed it was gonna be a game-crashing number of centipedes on cast. XP
