### ISSUE TITLE
ERROR: spell on experimental 11158 (latest google play version)

### ISSUE THREAD

**Issue by linonetwo** [chaosvolt/cdda-arcana-mod#167]
DEBUG    : ERROR: spell arcana_monster_archon_gaze_improved has invalid effect attack

 FUNCTION : void spell_type::load(const JsonObject &, const std::string &)
 FILE     : /var/lib/jenkins/workspace/Cataclysm-Android/android/app/jni/src/../../../../src/magic.cpp
 LINE     : 262

**Comment by linonetwo** [comment]
And it works fine in 11157 MacOS version

**Comment by chaosvolt** [comment]
That's odd, I'm guessing the google play version is out of date relative to the other versions. The spells using effect `attack` is a consequence of this PR: https://github.com/CleverRaven/Cataclysm-DDA/pull/44481

So it working on MacOS and Android is expected, having it not work on the google play version suggests it's out of date.
