### ISSUE TITLE
Selecting Wraithslayer in the crafting menu crashes the game

### ISSUE THREAD

**Issue by Daist** [chaosvolt/cdda-arcana-mod#170]
Mod crashes the game when selecting the Wraithslayer in the crafting menu with game telling that TORSO body part does not exist.
Fixed by editing "TORSO" to "torso" in ranged.json.

**Comment by chaosvolt** [comment]
Update Arcana, this was fixed by https://github.com/chaosvolt/cdda-arcana-mod/commit/5c51004c07f1afd441adedca0a253605bd9406a5
