### ISSUE TITLE
0.E-3

### ISSUE THREAD

**Issue by linonetwo** [chaosvolt/cdda-arcana-mod#172]
Have you tried this in 0.E-3? Seems loading progress to this mod crush the game. And there is no useful log in debug.log

**Comment by linonetwo** [comment]
Can you make a stable relese for e3?

**Comment by chaosvolt** [comment]
There is a release for 0.E stable but not sure if 0.E-3 broke compatibility with 0.E-2 (which that release was made for at first): https://github.com/chaosvolt/cdda-arcana-mod/releases

**Comment by linonetwo** [comment]
okay, but you have so many update recently, hope we can enjoy them with 0.E-3

What might be happened if game crush without any warning? Segment fault?

**Comment by linonetwo** [comment]
I know now, the crush isbdue to the lack of achievement system in 0.e-3, seems 0.e-3  lack lots of things from experimental.

I will still play experimental...So closing this.
