### ISSUE TITLE
vehicle part distorion_amp_motor_part has unknown or incorrectly specified install requirements vehicle_bolt

### ISSUE THREAD

**Issue by linonetwo** [chaosvolt/cdda-arcana-mod#176]
(continued from above) ERROR : src/veh_type.cpp:653 [static void vpart_info::check()] vehicle part distorion_amp_motor_part has unknown or incorrectly specified removal requirements vehicle_bolt

This is from experimental 11406, and I am always using the latest mod from Github.

**Comment by chaosvolt** [comment]
Cause is https://github.com/CleverRaven/Cataclysm-DDA/pull/46466, will have a fix in a bit.

**Comment by linonetwo** [comment]
Thanks for update!
