### ISSUE TITLE
Unrecognised JSON object on world loading

### ISSUE THREAD

**Issue by genisispig** [chaosvolt/cdda-arcana-mod#181]
>DEBUG    : Error: data/mods//Arcana/achievements.json: line 4:12: unrecognized JSON object

>[
  {
    "id": "achievement_arcana_npc_alexander",
    "type":
           ^
            "achievement",
    "name": { "str": "<color_cyan>(Arcana)</color> The Old Man" },
    "description": "Earn the trust of an old survivor.",

 >FUNCTION` : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 781

Placed the Arcana folder in my mods folder on game version 0.E-3.
Initially, the game wouldn't load until I changed id to ident in the modinfo.json folder. Now, I get this error when I attempt to make a new character in a world that has Arcana active.

**Comment by chaosvolt** [comment]
Use the 0.E Stable release if you're using the 0.E stable build of DDA: https://github.com/chaosvolt/cdda-arcana-mod/releases

**Comment by genisispig** [comment]
Ah yeah, I went to the effort of changing the config file without bothering to download the correct version. Thanks for the help and sorry for wasting your time!

**Comment by chaosvolt** [comment]
> Is the current master branch for the experimental branch?

Yep, one folder in it for DDA, one folder for BN.
