### ISSUE TITLE
Mantle of shadows bug

### ISSUE THREAD

**Issue by EpicMarble** [chaosvolt/cdda-arcana-mod#186]
Heya, I noticed a bug with the mantle of shadows where the effect of activating it seems to disappear from the item after exiting and restarting the game.

- Making the mantle (or spawning one) and using it in the same play session, it works like a charm. 
- After save & exit & getting back in the game, if:
   - the item was active on exit, the message of the invisibility dropping will show up even though the item remains in active state. Toggling the item off and on will play the messages, but no invisibility.
   - the item was not active on exit, toggling it will play the messages but no invisibility.

Tested it on the most recent experimental, fresh install with only this mod enabled + the default selected mods.

Love all your mods by the way. My zombie apocalypse just doesn't feel right without wrecking fungal blooms in my tank and I am grateful for that mod's revival. 🥇

**Comment by chaosvolt** [comment]
Oh right. This is caused by the exact same bug https://github.com/Noctifer-de-Mortem/nocts_cata_mod/pull/275 fixed if I recall.

Root cause is a DDA bug, basically. Root cause is: https://github.com/CleverRaven/Cataclysm-DDA/issues/49334

I'll commit a workaround in a bit, but underlying cause is a code problem.

**Comment by chaosvolt** [comment]
So, after playing around with it I've been able to fix it just about. Only issue that I can't do anything about is that save/load will still briefly cause many relic effects to need an extra turn to kick back in, so it prints the fade message for the invisibility effect despite promptly reactivating basically at the same time. But that's another "the hard code is a mess" issue I can't really do anything about.
