### ISSUE TITLE
death_function in Monsters JSON Needs Rework in Experimental

### ISSUE THREAD

**Issue by Nierfenhimer** [chaosvolt/cdda-arcana-mod#191]
As of Experimental builds after 10th July, JSON format for monsters has been adjusted to change expected syntax for "death_function". 
Previously, `[ "NORMAL" ]` was required for no effect on death, but can now be removed. 
All other functions have been adjusted, ex `[ "BROKEN" ]` is now `{ "corpse_type": "BROKEN" }`.

Included file has adjustments for a base to save some work/time, hopefully!

[monsters.txt](https://github.com/chaosvolt/cdda-arcana-mod/files/6796493/monsters.txt)

**Comment by chaosvolt** [comment]
Nice, thank you. Grabbing latest available build to test things out right now, then will commit the changes from it. I went ahead and gave a couple of the boss monsters more flavorful melt-away messages for the hell of it, but otherwise used the changes in the file as-is.
