### ISSUE TITLE
[Latest Experimental] Survivor zombies immediately breaks open the basement walls of the hidden cultists' houses, destroying stairs and other terrains on ground level.

### ISSUE THREAD

**Issue by ifffrt** [chaosvolt/cdda-arcana-mod#192]
Latest experimental versions has changed something about either the survivor zombies or the walls that surround the Arcana basements that made it so that the walls can get immediately destroyed whenever you create a lot of noises near them and attract the zombies' attention. This usually immediately destroys the floor in front of the stairs leading down, or even the stairs itself. It also leaves the zombies out in the open where players can conveniently poke them with a spear from the street. Both of which can either make going down the basement much harder or much easier, but can hardly be seen as the way it was intended to be played. Normal basements don't have this issue, because they are usually made with concrete walls, and don't normally have survivor zombies in them.

(I tested replacing the walls with brick walls and stone walls, and neither of them got destroyed by survivor zombies (not even veteran survivor zombies), so maybe you could change the walls to one of these?)

**Comment by chaosvolt** [comment]
Huh, weird. Will fix that in a bit. So just giving them stone walls should be good enough? I don't see any recent JSON changes that affect the base damage for standard survivor zeds, weird.

**Comment by ifffrt** [comment]
> 
> 
> Huh, weird. Will fix that in a bit. So just giving them stone walls should be good enough? I don't see any recent JSON changes that affect the base damage for standard survivor zeds, weird.

I'm not sure what is the reason either, but I remember there being talk of giving the Dark Days of the Dead more attention and features so that it can stand better on its own. One of which was making the regular zombies more bashing power as a group so that players can't nullify their danger completely by late game by building large reinforced structures (in that mod zombies can't evolve or revive). Maybe something in the code has enabled the survivor zombies to multiply their bashing power as a group better, since I remember in testing that a lone survivor zombie can't break down walls, but 2 of them can.

**Comment by chaosvolt** [comment]
Weird. Welp, working on hardening the walls plus updating underground locations to have soil in place of solid rock for z-level-minus-one areas.

**Comment by ifffrt** [comment]
Would you consider using a different wall other than stone wall for the basement? I kind of like the type of aesthetic the older regular wall gave. It gave this sort of chilling effect, like all of those horrible bloody occult kind of stuff somehow happened in an extremely plain setting. Like if you watch a snuff film it typically wouldn't take place in a dungeon in a castle but somewhere much more mundane (unless it was made in Germany or something). Or like in Silent Hill where the cult was ran by seemingly totally normal small town American types. It fits the tone better. Stone walls remind me too much of the basement of the Magic Academy in Magiclysm.

**Comment by chaosvolt** [comment]
Ah, guess I could do that. Guessing concrete walls would fit for that purpose.

**Comment by chaosvolt** [comment]
Okay, last two commits together should hopefully fix things, let me know if anything weird is still happening.

**Comment by ifffrt** [comment]
Will do. Btw, I also saw a flying polyp breaking open the ground of a strange grove and flying out. In case you don't want that happening.

**Comment by chaosvolt** [comment]
That also shouldn't be happening, unless they get out via the actual stairs, hmm. :/

**Comment by ifffrt** [comment]
Yeah well there was a hole on the ground and all.

The hole was still inside the tree circle itself though.

**Comment by ifffrt** [comment]
(But the flying polyp also broke open a bunch of the walls down there too. So maybe that's what made the ground collapsed).

**Comment by chaosvolt** [comment]
My guess is there's something fucky going on with collapse code in DDA now. I noticed while testing that some zeds were falling into a nearby basement from above due to having absolutely trashed part of the house it was under to the point of creating massive holes in the floor. All from maybe a dozen zeds tops, just basic day-one vanilla spawns at the default spawn rate.

I haven't seen this in 0.F Stable nor in Bright Nights so far.

So for the strange grove I'm guessing the best solution there is likewise replace the mundane t_wall with concrete wall, to retain the implication that the underground portion of the strange grove USED to look normal before becoming overgrown. I'll have to hope that root walls aren't excessively fragile, I haven't looked at them in a while.

**Comment by ifffrt** [comment]
Root walls were broken down in that strange grove too though. It could have contributed to the holes in the ground as well. The hole was way too large to be just from the normal wall collapsing, but if it was from the root walls too then there's no mystery.

**Comment by chaosvolt** [comment]
Well shit, that explains a lot. I'm not sure I can fix that without basically radically changing the strange grove, as the root walls are a big part of the structure's design, and there aren't any good alternatives. I could possibly use copy-from to make a mimicry of root walls that looks the same but has, but really the root (heh) cause here is that root walls are WAY weaker than solid soil despite presumably being solid roots worming their way through what's generally going to be soil.

I might suggest looking at how vulnerable locations are to zombie bash parties on day one in vanilla, and opening an issue to report it if it continues to look like something wacky is going on: https://github.com/CleverRaven/Cataclysm-DDA/issues

Something about the bash code has let them absolutely ruin basically any terrain that doesn't have stone-tier levels of damage requirements, and I'm not sure I can't easily do anything about that.

**Comment by ifffrt** [comment]
Maybe you could add an identical type of root wall that looks exactly like normal root wall, except as strong as, say, brick walls as a stop gap measure? Would also need to make an identical "normal" wall to replace the rest of the walls too of course, but on the plus size we now have an alternative type of wall to replace the too weak basement walls in the arcana houses that doesn't change its aesthetic.

**Comment by chaosvolt** [comment]
I could do that too, but a lot of basements now have concrete walls it seems, it would stand out a bit more seeing a variant of mundane walls being as tough as concrete, compared to root walls which have very few spawns in vanilla.

**Comment by ifffrt** [comment]
Maybe you could make it only as tough as brick walls? Brick walls were strong enough for the survivor zombies too. And the walls of the ground level facade of the houses themselves were already made of brick, so it makes a certain level of sense. And it makes irl sense too. Where I live walls are usually made with bricks and then plastered over, and they all look identical to the wooden paneled walls of the average American suburbian houses since it's the plastered outside that we look at. So maybe the new wall could be named "t_brick_wall_plastered" (with the materials adjusted to suit it).

**Comment by chaosvolt** [comment]
Hmm, guess that works too I suppose. For now though, hopefully the root problem should be solved, I hope?

**Comment by ifffrt** [comment]
Yeah I can confirm it's all good now. But no alternate brick wall? I was looking forward to that.

**Comment by chaosvolt** [comment]
I mean I guess I could, will do so later today when I get the chance.

**Comment by ifffrt** [comment]
Cool. Cool. Btw heads up. I saw some item in the mod is starting to throw an error. Said effect teleport_random is now invalid. Maybe you should check that out too.

**Comment by chaosvolt** [comment]
Implemented the lookalike walls and fixed the JSON error you mentioned. Also started the first hint of an idea I had...

**Comment by ifffrt** [comment]
Sounds exciting! I look forward to your new idea, whichever form it might takes.
