### ISSUE TITLE
Pseudo items is broken.

### ISSUE THREAD

**Issue by ifffrt** [chaosvolt/cdda-arcana-mod#194]
New PR https://github.com/CleverRaven/Cataclysm-DDA/pull/50347 from 4 days ago changed how pseudo items works. Now the game is throwing me errors about some items in the mod. 

It broke some things in the Cata++ mod too.

**Comment by chaosvolt** [comment]
Ah, fucked up the item IDs I'm guessing. I'll try to tackle it tomorrow if I can, likely to be busy.

**Comment by chaosvolt** [comment]
https://github.com/chaosvolt/cdda-arcana-mod/commit/45ad79759383f577eac748f5fd4ca968bdc83663 should fix it, but let me know if anything else crops up.
