### ISSUE TITLE
Question/Potential Bug: How does the displacement surge generator work?

### ISSUE THREAD

**Issue by Celepito** [chaosvolt/cdda-arcana-mod#195]
I havent found any links to a discord or something, so sorry I am doing this here if I missed something.

After raiding a Central Lab, I had the components to build one, and installed it in my mobile base. Said it provided 60 kW power, and filled up my storage batteries quite quick.

But now the output has dropped down to 59.6 kW at first, then to 58.5k, all within an in-game day, and I am not sure if this is intended or not. Driving around didnt increase the production, waiting didnt, and neither did turning it off and back on, nor ripping it out and reinstalling it.

So I am rather confused, since the item description talks about it being "a truly unlimited source of electrical energy", and an explanation would be nice. Or a bug fix, I guess.

Its getting late here anyway, so I'll stop playing for today, and leave this here in case a person who knows the answer lives in a different timezone/has a different sleep schedule.

**Comment by Celepito** [comment]
Nevermind, it seems the Reactor "lowers" its output in line with the amount of energy that is consumed. My rig with all the turrets and such just drew in 1.5 kW, and so it showed 58.5 kW as produced. Turning off the lights and the cameras brought down the need to 1k and in turn, the production showed 59k, so thats the issue, I think. No idea why I didnt think to check that before.

**Comment by chaosvolt** [comment]
Yep. It provides a continuous output of energy. It's unlimited in never running out, but actual power is somewhat low. More than the old vortex generators from blazemod to enough of a degree to be useful, but not enough to keep a motor going 24/7.
