### ISSUE TITLE
Invalid or misplaced field name and context

### ISSUE THREAD

**Issue by calrissian-tendra** [chaosvolt/cdda-arcana-mod#199]
I'm getting these three error messages on startup of Stable Build 0.F-2.

 DEBUG    : (json-error)
Json error: storage/emulated/0/Android/data/com.cleverraven.cataclysmdda/files/data/mods/Arcana/bionics.json:9:19: Invalid or misplaced field name "fake_weapon" in JSON data

    "occupied_bodyparts": [ [ "arm_r", 10 ], [ "hand_r", 5 ] ],
    "act_cost": "75 kJ",
    "fake_weapon":
                  ^
                   "bio_electrothermal_arc_projector_gun",
    "flags": [ "BIONIC_GUN", "BIONIC_NPC_USABLE" ]
  },

 FUNCTION : void JsonObject::report_unvisited() const
 FILE     : /var/lib/jenkins/workspace/Cataclysm-Android/android/app/jni/src/../../../../src/json.cpp
 LINE     : 122
 VERSION  : 0.F-2

and the second one:

 DEBUG    : (json-error)
Json error: storage/emulated/0/Android/data/com.cleverraven.cataclysmdda/files/data/mods/Arcana/bionics.json:19:19: Invalid or misplaced field name "fake_weapon" in JSON data

    "occupied_bodyparts": [ [ "arm_r", 10 ], [ "hand_r", 5 ] ],
    "act_cost": "60 kJ",
    "fake_weapon":
                  ^
                   "bio_rift_focus_projector_gun",
    "flags": [ "BIONIC_GUN", "BIONIC_NPC_USABLE" ]
  },

 FUNCTION : void JsonObject::report_unvisited() const
 FILE     : /var/lib/jenkins/workspace/Cataclysm-Android/android/app/jni/src/../../../../src/json.cpp
 LINE     : 122
 VERSION  : 0.F-2

and the third one:

 DEBUG    : Error: Json error: storage/emulated/0/Android/data/com.cleverraven.cataclysmdda/files/data/mods/Arcana/flags.json:6:5: missing required field "context" in object: {
    "id": "arcana_birchbark_weave",
    "type": "json_flag",
    "info": "This gear has been altered by druidic magic, increasing its <good>protection</good>."
  },

    "type": "json_flag",
    "info": "This gear has been altered by druidic magic, increasing its <good>protection</good>."
  },
    ^
  {
    "id": "arcana_tanbark_weave",
    "type": "json_flag",

 FUNCTION : bool main_menu::new_character_tab()
 FILE     : /var/lib/jenkins/workspace/Cataclysm-Android/android/app/jni/src/../../../../src/main_menu.cpp
 LINE     : 865
 VERSION  : 0.F-2

**Comment by chaosvolt** [comment]
You're using the experimental version of Arcana with 0.F Stable DDA. Use the correct release: https://github.com/chaosvolt/cdda-arcana-mod/releases/tag/0.F
