### ISSUE TITLE
Quest ideas and NPC additions

### ISSUE THREAD

**Issue by chaosvolt** [chaosvolt/cdda-arcana-mod#2]
I'll list a few ideas I had here, and anything presently hindering their addition. Any advice or interesting suggestions in this vein are welcome.

First idea entails NPCs. Now at least you can set NC class, something I wanted a damned long time ago. It even allows forcibly overriding the NPC's inventory, which would allow me to spawn an arcanist NPC that has appropriate gear as well as skillset. Problem is I see no way to use NC class overrides to ensure that miner things like underwear are applied sanely for male and female NPCs. The alternative would be ensuring their gear is 100% unisex.

Next idea is quest chains focused on the arcane locations. Ideally relevant NPCs would be added as quest-givers, and this presents an issue in how to handle that. Fixed NPCs could be rigged up to work just fine aside from having no idea where to spawn them. But for NPCs spawning "in the wild" there's no way to ensure a random NPC will be consistent in both NPC class and available quest.

Some rough quest-related thoughts:
* The three implied factions each having a quest chain. Problem here is that JSONized quests don't support revealing a desired target location, but "follow me here" MIGHT work.
* Kill targets aren't an option either. Chances are each quest chain would lead to needing to clear out the NPC's related location, and thus killing the boss would be an obvious conclusion.
* Any random fetch quests at least seem to be doable. Though regarding the above idea, a "bring me the location's unique item" idea would be a hacky way to do it. Plus somewhat idiotproof by ensuring you aren't stuck if you already cleared out the relevant location.

**Comment by Taberone** [comment]
In more recent experimental builds, accepting fetch quests like finding a relic will occasionally have NPCs marking locations (Museums, Cathedrals, etc) for you. Not sure if those quests are JSONized or not, however.

Not sure why "Kill target" wouldn't be an option. Make the "boss" monster (Dracolich, Archon, etc) for the arcana location the target?

Quest chains focused on the arcana locations sound nice.

Seems like gender-specific clothing for NPCs is already possible? The files for NPC classes like NC_COWBOY.json have things like this:

`{
    "type" : "item_group",
    "id" : "NC_COWBOY_pants_male",
    "items":[
      ["jeans", 70],
      ["pants", 20],
      ["pants_leather", 20],
      ["pants_cargo", 20]
    ]
  },{
    "type" : "item_group",
    "id" : "NC_COWBOY_pants_female",
    "items":[
      ["jeans", 70],
      ["pants", 20],
      ["pants_leather", 20],
      ["pants_cargo", 20],
      ["skirt", 10]
    ]
  },`

If it's still not possible somehow, I'd be fine with unisex gear.

**Comment by chaosvolt** [comment]
I'm fairly certain that the "reveal map location" is due to hardcoded stuff last I checked. Likewise, gender-specific NPC gear is again due to their gear using hardcoded stuff. Hell, the only way you can even specify new ones is via the override feature added so that the bee NPC can rush at the player naked.

Another new complication I've found is that I'd logically want to add NPCs to new locations, but all the existing structures and official mods are REALLY pushing the hardcoded limit for how many mandated mapgen specials can exits. Easiest way around that would be to set the minimum for any new places to 0.

**Comment by chaosvolt** [comment]
Welp. I'm annoyed now. I decided I'd at least test adding NPC classes and allowing overrides for their gear, since there's 2 NPCs already that do that.

So after sorting out the obligatory load errors, I started spawning NPCs to see if the mage loadouts were working. Spawn, examine, kill. After the bodies had piled up to the point where NPC drops were spilling out onto adjacent spaces. Something clicked in my head and I figured out the idea of examining their class using the edit player/NPC option. So a few NPCs later I spot a Blood Mage with no weapon and normal survivor clothes.

So, turns out I can't even get fucking NPC classes to work. Fuck it, pinging I guess @BorkBorkGoesTheCode and @DangerNoodle so one of them can go report that, if it isn't already reported. Far as I can tell the carried/worn/weapon overrides SHOULD work, but they don't for custom entries. Assuming it's literally only hardcoded to accept EMPTY_GROUP and the NC_DEBUG entries, which would be the most convoluted, idiotic implementation possible.

I'd have to figure out how to test that debug NPC to see if this shit even works for them, or if it works but uses hardcoded behavior. Not really that eager to start testing an issue I can't even report on.

**Comment by DangerNoodle** [comment]
Question. Did you mean fixed unique NPCs with their own set NC files, or did you mean the randomized classes seen with the initial NPC and 

I tested the former by creating a basic copy of the arsonist class, then added overrides so that they would spawn in a full set of fire fighter equipment, and a fire axe as a weapon, then gave the fixed arsonist NPC this class. Reaching a refugee center confirmed it functioned as expected.

**Comment by chaosvolt** [comment]
...hmm. I can use that then. Random NPCs being arcanists might be a bit silly anyway.

**Comment by DangerNoodle** [comment]
So you did mean dynamic and initial NPCs were affected by your observed issue?

**Comment by chaosvolt** [comment]
...doh. Forgot to actually answer that, then got busy for most of the day, kinda just got home. And yeah, I only tested this with the random NPCs, so seems the problem's with just them.

Sorry. @_@

**Comment by DangerNoodle** [comment]
It is fine, just wanted to confirm the apparent problem before attempting further testing.

**Comment by chaosvolt** [comment]
Update: Mlangsdorf's work in this area has made these ideas overall entirely more doable than they were back when I had this idea, and I've taken the first step towards implementation via https://github.com/chaosvolt/cdda-arcana-mod/pull/50.

I have further plans, but for now the current first step is what I've focused on, as it isn't dependent on several other NPC quest chains potentially interacting with each other. I have plans for NPCs related to the other two factions, but they'll both potentially involve more than one NPC, possibly even faction shenanigans and such. Just all the effort that went into the hermit's dialogue proved more exhausting than I expected, and even then I'm not 100% done with it. Regardless, I think I can officially close this.
