### ISSUE TITLE
"No Such Trap" error when starting new game with latest Arcana mod

### ISSUE THREAD

**Issue by Taberone** [chaosvolt/cdda-arcana-mod#20]
<a href="https://imgur.com/RQsESLI"><img src="https://i.imgur.com/RQsESLI.png" title="source: imgur.com" /></a>

Tested by creating a new world with only Arcana mod and it gives this error before booting me to the main menu.

**Comment by chaosvolt** [comment]
...have you tried the newest version of this mod?

**Comment by chaosvolt** [comment]
Oh. Wait. *AAAAAH* fuck. I forgot one mapgen file that has those damn things.

**Comment by chaosvolt** [comment]
Should be the last of those occurrences fixed now. It would've been nice if @Night-Pryanik had retained the trap entry as a migration/legacy thing to prevent stuff like this, but eh.

Tell me if I somehow missed any others.
