### ISSUE TITLE
The ring of the fallen angel and the jade wreath don't work properly.

### ISSUE THREAD

**Issue by ifffrt** [chaosvolt/cdda-arcana-mod#200]
These two items didn't work in my game. The jade wreath was able to protect me against heat, but couldn't protect me against direct flame. The ring of the fallen angel meanwhile let me get wrecked by a M249 turret, despite saying it would completely protect me against bullets (not sure about blades, is it supposed to help against all cut damage? because I got bit by a zombie snapper like normal while putting it on).

And I'm not sure if this applies, but the meteoric talisman also let me sustain some moderate damage in my fight against the Host of the Archon. Not sure if that counts.

**Comment by chaosvolt** [comment]
That's...odd. I double-checked just to make sure and both items give the correct effect, `Ward Against Flame` and `Holy Ward`. Check your effects screen when you use them. If they say `Ward Against Heat` and `Ward Against Evil` instead, some kind of JSON fuckery is going on sucj that you're somehow not using a fully up to date version of Arcana.

If they do say the correct effect names then something else is going on, and I'd need to look into it further. Whether you're using DDA or BN for example.

**Comment by chaosvolt** [comment]
AHAH! It's DDA-specific, caused by https://github.com/CleverRaven/Cataclysm-DDA/pull/47633 changing the flag name used for this stuff.

Will fix in a moment.

**Comment by ifffrt** [comment]
> 
> 
> AHAH! It's DDA-specific, caused by [CleverRaven/Cataclysm-DDA#47633](https://github.com/CleverRaven/Cataclysm-DDA/pull/47633) changing the flag name used for this stuff.
> 
> Will fix in a moment.

Very weird that it failed silently though. Should I make an issue about that?

**Comment by chaosvolt** [comment]
Might be worth it to do so, yeah. Flags USUALLY fail loudly, in fact I ran into that with https://github.com/chaosvolt/cdda-tankmod-revived-mod/issues/3 so it seems they can't keep flag error-handling consistent.
