### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Colliwobble** [chaosvolt/cdda-arcana-mod#201]
Keep getting this crash on the 2021-09-09-0239 build of experimental cata. Updating Arcana did not fix the issue.
![arcana error](https://user-images.githubusercontent.com/90429122/132779185-d89948a0-cdb5-4522-abcf-dd15a3b08bfa.jpg)

**Comment by chaosvolt** [comment]
Was just earlier made aware of that, working on that and some other fixes now.
