### ISSUE TITLE
item group "NC_JUNK_SHOPKEEP_misc" already defined with type "collection"

### ISSUE THREAD

**Issue by linonetwo** [chaosvolt/cdda-arcana-mod#202]
DEBUG : Error: item group "NC_JUNK_SHOPKEEP_misc" already defined with type "collection"

FUNCTION : bool main_menu::new_character_tab()
FILE : /home/runner/work/Cataclysm-DDA/Cataclysm-DDA/android/app/jni/src/../../../../src/main_menu.cpp
LINE : 857
VERSION : adf846b

**Comment by linonetwo** [comment]
Seems sometimes we can't reuse id across type.

**Comment by chaosvolt** [comment]
Update Arcana, make sure you're using the correct version. This should already be fixed by this: https://github.com/chaosvolt/cdda-arcana-mod/commit/77073c4df8bda2178c541aa9af5482567a5de5a9

See issue: https://github.com/chaosvolt/cdda-arcana-mod/issues/201

**Comment by linonetwo** [comment]
Ok, thanks. Our project is 2-3 levels downstream of Arcana, so there are some delays... Our community is using Arcana-KenanPack-KenanPackChinese-QQGroupFileupload ...

I will port this to downstream, thank you for the update.

**Comment by chaosvolt** [comment]
Ah right, sorry for the delays. Still haven't the chance to look into translations just yet, been juggling a lot.

**Comment by linonetwo** [comment]
Currently, there is no way to translate other than creating a new translated mod, so we have created https://github.com/linonetwo/CDDA-Kenan-Modpack-Chinese , and we have a group of translators working on it.

And as you know, it contains Arcana, so we actually are playing well translated Arcana now~

**Comment by linonetwo** [comment]
I have ported your fix to kenan pack https://github.com/Kenan2000/CDDA-Kenan-Modpack/pull/164
