### ISSUE TITLE
IMMUNE effects seems to be totally broken even with correct names.

### ISSUE THREAD

**Issue by ifffrt** [chaosvolt/cdda-arcana-mod#203]
I just got a chance to test the corrected effect names in-game by stepping into another fire with the Jade Wreath active and it seems to be still broken. I don't know what the issue is. The flag names seem correct to me.

**Comment by ifffrt** [comment]
Just tested giving my character the "debug_full_protection" effect from Magiclysm, and it seems the issue isn't with the effects themselves. The IMMUNE effects seem to work fine in regards to protecting you from electricity and acid. So it seems the problem might be because "HEAT_IMMUNE" only protects you against heat, not flame.

**Comment by ifffrt** [comment]
I just tested giving the "HEATPROOF" flag to the debug_full_protection effect and it seems to be working. But it doesn't protect your gears from the flame, only you. Not sure if protecting your gear as well as you is how the wreath was supposed to work but I kept on trying other stuff anyway. I then tried giving the character an aura with the "HEATPROOF" flag, which works about the same. Only protected you, not your gear. Then I looked into the possibility of giving the aura itself a custom material with extremely high fire_resist value like how turnout gears get their fire protection from the nomex material by default, but it didn't seem to be an option. 

What finally worked was giving the test aura an "ARMOR_HEAT" value with a multiplier value of -1.0 (using this line `"relic_data": {
      "passive_effects": [ { "has": "WORN", "condition": "ALWAYS", "values": [ { "value": "ARMOR_HEAT", "multiply": -1.0 } ] } ]
    }`). It finally completely protected both me and my gears from burning up, and even after passing time for 30 minutes while standing in a fire vent none of my clothing got destroyed.

![debug aura](https://user-images.githubusercontent.com/74819253/133424974-9215ed63-8671-421d-a22f-3cd42d368b30.jpg)

Anyway, here's the full code to the test aura I used: 

  {
    "id": "flame_proof_aura",
    "type": "ARMOR",
    "name": "test fireproof aura",
    "description": "sdjifojcxvolk",
    "weight": "1g",
    "volume": "1ml",
    "price": 3646,
    "symbol": "o",
    "color": "green",
    "flags": [ "AURA", "SEMITANGIBLE", "OVERSIZE", "ONLY_ONE", "TRADER_AVOID", "NO_TAKEOFF", "NONCONDUCTIVE", "HEATPROOF" ],
    "relic_data": {
      "passive_effects": [ { "has": "WORN", "condition": "ALWAYS", "values": [ { "value": "ARMOR_HEAT", "multiply": -1.0 } ] } ]
    },
    "armor": [
      {
        "covers": [ "leg_l", "leg_r", "torso", "arm_l", "arm_r", "hand_l", "hand_r", "head", "foot_l", "foot_r", "mouth", "eyes" ]
      }
	]
  },

**Comment by chaosvolt** [comment]
That is...weird. This looks like a combination of fuckery, from the immunity flag not protecting items to enchantments taking a turn to kick in after you load a save.

I'm about to be heading out so I'm going to have to dissect this properly and fix it when I get home.

**Comment by ifffrt** [comment]
Actually it's only the Jade Wreath that wasn't working properly because of the wrong effect name. I was a bit hasty when I first tested this. Other items like the Meteoric Talisman seems to work fine. The issue is that "HEAT_IMMUNE" doesn't really protect you from direct flame exposure for some reason.

**Comment by chaosvolt** [comment]
Huh, that's weird. Give me a bit and now that I'm back I'll check this.

**Comment by chaosvolt** [comment]
Okay I'm looking at this and it shows that the jade wreath does give the `heat_ward_true` effect in both the BN and DDA version of Arcana, and in the DDA version it correctly uses the `HEAT_IMMUNE` effect, so that doesn't make any sense. Let me try and test this some.

**Comment by chaosvolt** [comment]
Okay. Yeah, the effect given uses the correct effect flag, which means that whatever is going on is a mistake on DDA's end. The jade wreath works just fine in BN, as do any other sources of heat immunity from effects. I'd suggest you open an issue explaining that `HEAT_IMMUNE` is broken when the source is an effect: https://github.com/CleverRaven/Cataclysm-DDA/issues/new/choose

The jade hauberk itself burning up is something I'm fairly certain I can fix, but don't know if I can make it protect other items against fire.

**Comment by chaosvolt** [comment]
Yep, it protects your other clothes just fine. Whatever they broke with `HEAT_IMMUNE` in DDA, it's definitely on their end. Do tell me how the issue goes and if they fix it, I guess.

**Comment by ifffrt** [comment]
Was the jade wreath supposed to protect your clothes as well or is it only the jade hauberk that does that?

**Comment by chaosvolt** [comment]
> Was the jade wreath supposed to protect your clothes as well or is it only the jade hauberk that does that?

I'd need to figure out a way to implement it so that effects can also protect your clothes. It's easy with the jade hauberk since it can have active relic data, not so much with anything that grants an effect since those can't have enchantments.

And yes, that's very obviously the mistake they made. Did you open an issue for it? Because I don't expect them to find out about it on their own.

**Comment by ifffrt** [comment]
While we wait for them to fix this, maybe a stop gap measure could be used by giving the heat_ward_true the "FIREPROOF" flag. This way the Jade Wreath can have some functionality back.

**Comment by chaosvolt** [comment]
Hmm, I'll give it a test then.

An alternative would be to make it so the jade hauberk is an item you toggle on and off like the jade hauberk, that would fix clothes burning up when you're using it.

The Dragonblood and PoTV spells would still be unable to protect your items if they still use effects only, but I suppose it does mean the jade wreath retains a useful niche even with spells competing with it.

**Comment by ifffrt** [comment]
Those spells could summon a wearable, expirable aura which has the `HEATPROOF` flag (and also made from Essence or something fireproof so they don't burn up after loading in). I just tested and giving the `HEATPROOF` flag to an aura is sufficient to protect all your clothes from burning up (don't know why it didn't work in my original testing, but it works now).

**Comment by chaosvolt** [comment]
Spawning aura items is a hack I prefer not to use unless absolutely necessary. If effects could cite enchantments I would be able to eliminate basically every instance of "use item/cast spell to summon another item that gives you the necessary relic data"

**Comment by ifffrt** [comment]
By enchantments do you mean the field named "passive_effects"?

**Comment by chaosvolt** [comment]
Yeah, basically. Mutations and CBMs are able to access enchantments, but not effects.

That said, when I get the time and energy I think I will convert the jade wreath to an item you toggle on and off, in both the DDA and BN versions, as that affords the player a bit more control over when they'll be expending essence to gain elemental buffs.

**Comment by ifffrt** [comment]
Hmm. Getting passive_effects to become available to enchantments sounds pretty valuable for some of my weirder Crazy Cataclysm ideas. Not sure how I would use them exactly, but maybe I could think of something so that I could make a push for it.

**Comment by chaosvolt** [comment]
Good luck, might look into porting it over to BN as well if it works decently.
