### ISSUE TITLE
some kinda crash 

### ISSUE THREAD

**Issue by SirClarke** [chaosvolt/cdda-arcana-mod#204]
DEBUG    : Error: Json error: data/mods/Arcana/npcs/TALK_BLOOD_MAGE_SHRIKE_SPLINTER.json:268:24: u_buy_item expecting a non-zero cost parameter

      "effect": [
        { "npc_add_var": "elena_blade_help", "type": "flag", "context": "shrike", "value": "yes" },
        { "u_buy_item":
                       ^
                        "book_bloodmagic" }
      ]
    },

 FUNCTION : bool main_menu::load_character_tab(bool)
 FILE     : src/main_menu.cpp
 LINE     : 1143
 VERSION  : 8ba81b4

**Comment by ScarPan** [comment]
can confirm, encountered same issue when creating a character for Worlds with Arcana DDA mod enabled.

**Comment by chaosvolt** [comment]
Looks like they made cost_num mandatory instead of defaulting to zero for some insane reason, let me see if I can get a quickfix out.

**Comment by chaosvolt** [comment]
There we go, https://github.com/chaosvolt/cdda-arcana-mod/commit/396015fcc0887e03a1c33115970c370a379efee4 should fix things.

**Comment by ScarPan** [comment]
> There we go, [396015f](https://github.com/chaosvolt/cdda-arcana-mod/commit/396015fcc0887e03a1c33115970c370a379efee4) should fix things.

Thank you for the kind update and the swift fix! Have a nice day.

**Comment by SirClarke** [comment]
Thanks alot
