### ISSUE TITLE
invalid spell id "arcana_seal_*"

### ISSUE THREAD

**Issue by GrayAegis** [chaosvolt/cdda-arcana-mod#206]
Whenever I try to look at an Arcana seal, I get this. Happens with every arcana seal item. Crafting the item anyway and activating it crashes the game with no debug log file that I can see.

Downloaded the latest version from two days ago, where the spell IDs were changed from "arcana_magic_*" to "arcana_seal_*"

```
DEBUG    : invalid spell id "arcana_seal_agility"

 FUNCTION : const T& generic_factory<T>::obj(const string_id<T>&) const [with T = spell_type]
 FILE     : src/generic_factory.h
 LINE     : 445
 VERSION  : bbd6a9d
```

**Comment by chaosvolt** [comment]
Someone pointed out a mistake I made while adding different spells for the magic seal items, most recent commit was a fix for it.
