### ISSUE TITLE
Missing context field in various objects

### ISSUE THREAD

**Issue by MaxGilbreath** [chaosvolt/cdda-arcana-mod#207]
Full error below, causes crash to title:

 DEBUG    : Error: Json error: data/mods/Arcana/flags.json:6:5: missing required field "context" in object: {
    "id": "arcana_birchbark_weave",
    "type": "json_flag",
    "info": "This gear has been altered by druidic magic, increasing its <good>protection</good>."
  },

    "type": "json_flag",
    "info": "This gear has been altered by druidic magic, increasing its <good>protection</good>."
  },
    ^
  {
    "id": "arcana_tanbark_weave",
    "type": "json_flag",

 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 952
 VERSION  : 0.F-2

**Comment by MaxGilbreath** [comment]
Forgot to mention, this is with CDDA 0.F -2

**Comment by chaosvolt** [comment]
Use the correct version: https://github.com/chaosvolt/cdda-arcana-mod/releases/tag/0.F
