### ISSUE TITLE
duplicate item

### ISSUE THREAD

**Issue by fivesea** [chaosvolt/cdda-arcana-mod#213]
DEBUG    : Error: Json error: data/mods/Arcana/items/tool_armor.json:613:59: duplicate item in set defined by json array

        "coverage": 100,
        "covers": [ "torso", "arm_l", "arm_r", "leg_l", "leg_r" ],
        "material": [ "iron", "copper", "leather", "iron" ]
                                                                         ^
                                                           ,
        "material_thickness": 7,
        "environmental_protection": 1

 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 859
 VERSION  : 564d632

==============

iron listed twice, i've removed on my end and works now. thought i'd let you know

**Comment by chaosvolt** [comment]
Huh, that's odd. Looks like at some point I accidentally changed cotton to a redundant iron in the material entry for jade hauberk. Thanks for spotting that.

**Comment by chaosvolt** [comment]
That should fix it, tell me if anything else comes up.
