### ISSUE TITLE
invalid monster flag: "ABSORBS_SPLITS"

### ISSUE THREAD

**Issue by waveyl** [chaosvolt/cdda-arcana-mod#220]
https://github.com/CleverRaven/Cataclysm-DDA/pull/53741

**Comment by waveyl** [comment]
DEBUG    : (json-error)
Json error: data/mods/Kenan-Modpack-Chinese/Arcana/mutations/mutations_dragonblood.json:652:28: Invalid or misplaced 
https://github.com/CleverRaven/Cataclysm-DDA/pull/53603

**Comment by chaosvolt** [comment]
Thanks for spotting those.

https://github.com/chaosvolt/cdda-arcana-mod/commit/960b42830ec3f02c3a702ba3b78a016f7a32d334 should fix it, let me know if anything else comes up.

**Comment by waveyl** [comment]
Same stamina problem in Cata++.

**Comment by waveyl** [comment]
trait SELFAWARE for profession bio_weapon_b does not exist (Cata++)
https://github.com/CleverRaven/Cataclysm-DDA/pull/53802

**Comment by chaosvolt** [comment]
Ack, I'll work on a Cata++ fix in a bit then.

**Comment by chaosvolt** [comment]
And https://github.com/Noctifer-de-Mortem/nocts_cata_mod/pull/335
