### ISSUE TITLE
misspelled broght

### ISSUE THREAD

**Issue by TadhgEomonn** [chaosvolt/cdda-arcana-mod#224]
In Valzain dialogue, reply to Any stories? query.

Valzain: What stories have you broght me?

brought

**Comment by chaosvolt** [comment]
Whatever this is it's not an Arcana NPC.

**Comment by TadhgEomonn** [comment]
Sorry, must magiclysm.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by chaosvolt** [comment]
Yeah, Magiclysm is @korggent's mess, not mine. You've got the mods mixed up.
