### ISSUE TITLE
Game crashes when trying to mutate.

### ISSUE THREAD

**Issue by sephonjay** [chaosvolt/cdda-arcana-mod#226]
So yeah, the game crashes when I try to mutate via Restored Ritual blade and eventually Sacramental Heart when I got my hands on that.
Let's see...

**Mods in the world:**
 -"dda",
 -"Arcana",
 -"package_bionic_professions",
 -"magiclysm",
 -"crt_expansion",
 -"blazeindustries",
 -"no_npc_food",
 -"no_fungal_growth",
 -"MMA",
 -"my_sweet_cataclysm",
 -"extra_mut_scens",
 -"crazy_cataclysm",
 -"Mining_Mod",
 -"DinoMod",
 -"speedydex",
 -"stats_through_kills"

**Steps to recreate:**
-Make character
-Spawn Restored ritual blade/Sacramental Heart
-Activate either item

**Things I've tried**
-Updated to latest experimental
-Updated Arcana (deleted the old folder etc.)
-Made a new world and character with just Arcana and DDA.

Here's the crash log for the attempt with just Arcana and DDA:

[crash.log](https://github.com/chaosvolt/cdda-arcana-mod/files/7967682/crash.log)

**Comment by chaosvolt** [comment]
Will look into it in a bit. Not sure if any recent DDA changes are to blame.

**Comment by chaosvolt** [comment]
So far as I can tell, some change at some point broke the mutagen action being called from a tool instead of a comestible. Unless I stumble into some other specific cause, I'll have to basically rig up a hacky solution where using the items in question create a separate mutagenic item instead. :/

**Comment by sephonjay** [comment]
I made a post about this on reddit before I went here, and apparently someone figured something out.

https://www.reddit.com/r/cataclysmdda/comments/sgchmw/game_crashes_when_i_try_to_mutate_arcana_and/

**Comment by chaosvolt** [comment]
All of those are likely comestibles rather than tools, so that's probably the issue. If I get time later today I'll do the workaround, just been busy with offline stuff lately.

**Comment by sephonjay** [comment]
Yup, that's fixed it. Thanks my dude.
