### ISSUE TITLE
Vitamin rates have changed for C:DDA

### ISSUE THREAD

**Issue by chrispikula** [chaosvolt/cdda-arcana-mod#229]
Dragonblood mutations have a "vitamin_rates" tag.  

See:
https://discord.com/channels/598523535169945603/598523535169945607/939264607434977281
![image](https://user-images.githubusercontent.com/22281606/153459864-31c48704-0fc3-4ae9-9e73-8ec1ee45ba88.png)

I changed ARCANA_DRAGONFIRE to -5, -5, ARCANA_INNERFIRE to -10, -10, and ARCANA_INNERHEAT to -25, -25.  Otherwise gaining the mutations makes you lose blood and redcells over time.

**Comment by chaosvolt** [comment]
Pfft, nice. Will fix in a bit.
