### ISSUE TITLE
Blessing: Open doesn't work at spell level 6 and above.

### ISSUE THREAD

**Issue by sephonjay** [chaosvolt/cdda-arcana-mod#231]
The spell Blessing: Open you get from the Paragon of the Veil line stops working when you reach level 6 up to it's max of 20.

**Tested on**
-Safes
-Metal doors
-Wooden doors
-Chainlink fence gates

Incidentally, the Magic Sign version of it works just fine even on max level (at 10).

**Comment by chaosvolt** [comment]
That's odd. Its damage (what ter-transform uses to determine success rate) is fixed, meaning it does not change with level. The Magic Sign version does something similar with its "spike" effect, with failure rate only present for its AoE.

Is this on BN or DDA?

**Comment by chaosvolt** [comment]
Do tell if any other problems come up.
