### ISSUE TITLE
Old man odd house investigating noises by portal storm.

### ISSUE THREAD

**Issue by zakhad** [chaosvolt/cdda-arcana-mod#235]
Old man from odd house investigating noises caused by a portal storm which will likely lead to his demise, perhaps no windows on 2nd floor or metal grates instead?

![image](https://user-images.githubusercontent.com/5264667/156974746-f6898f87-6f08-4389-9e0d-86144cb808ee.png)
![image](https://user-images.githubusercontent.com/5264667/156974753-d5b7d8f0-cd63-4fc7-b913-9a8c65dd97e2.png)

**Comment by chaosvolt** [comment]
His investigate-only zone is already set to confine him inside the house. Just in case I've just now edited it to restrict him even more: https://github.com/chaosvolt/cdda-arcana-mod/commit/b01dbb9427ca90b0dbaf6c64faaa8455e81c1f97

Looks more like a DDA problem only,if portal storms can cause lethal threats to force their way into buildings via boarded up windows then that needs to be reported as a problem on their end: https://github.com/CleverRaven/Cataclysm-DDA/issues/new/choose

**Comment by zakhad** [comment]
![image](https://user-images.githubusercontent.com/5264667/156976973-f4b4a42f-debb-41e8-8015-0a1d1cbaae26.png)
They don't damage to buildings, it was him investigating the noise and smashing a window. The damage they cause is fatigue damage so they'll eventually fall asleep, and once you're asleep they start doing damage if i remember correctly.  The npc is less investigatory, and has decided this is his new location and doesn't move, just pokes things as they enter, but occasionally gets hit by them.

**Comment by chaosvolt** [comment]
That's odd. He should not even be investigating that far in the first place given the zone doesn't cover the windows. :/

**Comment by chaosvolt** [comment]
https://github.com/chaosvolt/cdda-arcana-mod/commit/cc81b7d5417c524a67cd2552c59954d5a8d2071d should beef things up further, including implementing a barred window variant so that should stop this from happening again.

**Comment by zakhad** [comment]
If i have any other feedback i can make another ticket but i believe this resolves it thank you for your time.
