### ISSUE TITLE
Arcana breathability bug cannot load the save. 

### ISSUE THREAD

**Issue by zakhad** [chaosvolt/cdda-arcana-mod#236]
Unable to update to 9be480c48c4cc171a9cf64aefaf519c63ab864be
![image](https://user-images.githubusercontent.com/5264667/157370983-8f3426df-f4b9-40de-b270-7f47c2dfbc1d.png)

**Comment by zakhad** [comment]
I'm able to update to the previous version, cc81b7d5417c524a67cd2552c59954d5a8d2071d posted on the 7th.

**Comment by chaosvolt** [comment]
Update your build of DDA, breathability stuff should be in sync with changes from https://github.com/CleverRaven/Cataclysm-DDA/pull/55662

**Comment by zakhad** [comment]
Ah okay,  cheers, will do when the launcher makes it available it's currently not letting me update anything past a week ago for some reason 
![image](https://user-images.githubusercontent.com/5264667/157383079-1f412533-7470-4dfb-81c3-bf36f56d2e93.png)

**Comment by chaosvolt** [comment]
Ah, nice. I'd suggest either updating things manually, or seeing if Catapult will be a bit less of a janky mess than Remyroy's launcher: https://github.com/qrrk/Catapult

**Comment by zakhad** [comment]
Yeah i've switched over to catapult that took a few hours of working out how things work copying settings/files over. Got a different arcana error but i believe this one was resolved.
