### ISSUE TITLE
Air talisman doesn't currently include the new mutant raw brains.

### ISSUE THREAD

**Issue by zakhad** [chaosvolt/cdda-arcana-mod#240]
![image](https://user-images.githubusercontent.com/5264667/157843387-229ba385-1e6f-49d6-bc24-26cb3aa7fa22.png)

![image](https://user-images.githubusercontent.com/5264667/157843504-e349a9b6-1825-4166-872c-f2c3c60bb276.png)

**Comment by chaosvolt** [comment]
Ah, nice. I'll add that in a bit I guess.
