### ISSUE TITLE
Updated arcana and i keep getting prompted to place an earth talisman shelter? 

### ISSUE THREAD

**Issue by zakhad** [chaosvolt/cdda-arcana-mod#241]
![image](https://user-images.githubusercontent.com/5264667/158013188-fa836d93-4e73-4db6-b7bb-6223d7b5d619.png)

**Comment by zakhad** [comment]
![image](https://user-images.githubusercontent.com/5264667/158013239-8a1bccfd-ebb4-4544-96fd-78febbb9615c.png)
Upon loading my game, i suspect i should have deleted the item before loading my save?

**Comment by zakhad** [comment]
![image](https://user-images.githubusercontent.com/5264667/158013255-b8a30bb1-21fd-4147-a2d1-dfbaec615e55.png)

**Comment by zakhad** [comment]
![image](https://user-images.githubusercontent.com/5264667/158013277-95fdffce-e79e-4322-81db-6cdc72780e77.png)
Tried teleporting, won't let me exit or place it down or anything.

**Comment by zakhad** [comment]
![image](https://user-images.githubusercontent.com/5264667/158013372-2e17ac1a-d4d0-4269-bcb0-13d3adf86b7b.png)
Loading the old version of the mod, destroying the item from an item stash of where it was located (It wasn't on my person)  and then loading the new version fixed the issue but a warning perhaps should be noted about people who update who might encounter a similar issue.

![image](https://user-images.githubusercontent.com/5264667/158013462-5a21dae7-1230-4e3f-80ef-b9c4c4b13c3a.png)

**Comment by chaosvolt** [comment]
I didn't know that was a thing not that it could even happen, and I don't know if there's any way to prevent it from happening. DDA's code be weird, it seems. :/
