### ISSUE TITLE
[DDA] Sofia's Trade Agreement quest issue

### ISSUE THREAD

**Issue by nemesis688** [chaosvolt/cdda-arcana-mod#242]
I'm having a bit of trouble doing Sofia's quest with the Trade Arrangements. It seems it should be turned into the merchant in the lobby named "Smokes" but I don't have any options with him related to the Church whatsoever. I checked with everyone else and not seen any options with them either for the quest.

Poking around in the files it seems he should have some dialogue related to the Church as well that's not there. I'm not really sure how dialogue gets assigned to NPCs though so I could be misunderstanding it.

The only other bit of info that might be relevant that I can think of is that I do have two unfinished quests with the NPC.

DDA Build from 2022-03-08 1811

**Comment by chaosvolt** [comment]
Looks like the old evac merchant has been replaced with this new custom NPC.

**Comment by chaosvolt** [comment]
Bit of a hacky fix to be honest but not many easy ways to do it given what talk topics you could into by mistake if I tried to streamline things. Do let me know if anything else comes up.

**Comment by nemesis688** [comment]
Thanks for quick look and fix!
