### ISSUE TITLE
Demi human flesh to be added to blood essence conversion recipe?

### ISSUE THREAD

**Issue by zakhad** [chaosvolt/cdda-arcana-mod#244]
Even though it's rotten regardless, should demi-human-flesh be another viable option for this recipe? it was a gracken that i butchered that i got this flesh from. 

![image](https://user-images.githubusercontent.com/5264667/159798783-a90bd5e9-1db0-42d5-b1d1-cee46d72ad2c.png)
![image](https://user-images.githubusercontent.com/5264667/159798848-f7f2b599-a249-432e-8d16-6be80dbdb061.png)

**Comment by chaosvolt** [comment]
Ah right, seems like it'd be fine to include.

**Comment by chaosvolt** [comment]
That should do it, do point out if I missed anything.
