### ISSUE TITLE
Summoned creatures followed me downstairs and now won't come back up (Bright Nights version, probably present in both)

### ISSUE THREAD

**Issue by Proxiehunter** [chaosvolt/cdda-arcana-mod#245]
While this seems to be an extension of a known issue in Bright Nights (and possibly DDA) where things like horses or other livestock will sometimes follow the player into a basement and then refuse to resurface it occurs to me that summons from Arcana mod have a possible fix of allowing the player to **un**-summon and then re-summon them above ground. Possibly adding a cost in stamina and/or pain and/or physical damage to make it less tempting to un-summon and re-summon during a fight since I assume the re-summon will be at full health.

In the mean time, is there a way to de-bug my summons back to the surface so they're useful again?

**Comment by chaosvolt** [comment]
Problem with that is there's no actual item use action or spell effect that could really "unsummon" a monster in any useful capacity. Closest you could get to that would be either using a pet carrier type item, which...has drawbacks:
![image](https://user-images.githubusercontent.com/11582235/160730669-fa4a9b5b-1d46-4f7f-9a70-d3e22425d07a.png)

As far as debugging it, not sure. One thing I'd like to do sometime for BN would be to port over the PR that lets you leash and lead tamed animals, that SHOULD work up and down stairs (but no telling if they tested that in DDA). It's on the issue listing various things to port over someday. ^^"

**Comment by Proxiehunter** [comment]
That's disappointing. I'm not sure there's an existing pet carrier item that would hold them but if there were I could just drag it upstairs. If my character can drag a zombear they can drag a Migo in a box.

Eventually resorted to using cheat mode to kill them and cheating their glyphs back into existence so I could bring them back. In the future I'll have to keep rope on hand and tie them in place before going up or down stairs. 

Unfortunately that means summons are currently only usable on the Z-level you summoned them on because if you take them down stairs you won't get them back without using the cheat menu.

**Comment by chaosvolt** [comment]
Yeah, one could mod in a pet carrier item with a higher size capacity but weight would still be very punishing to deal with for most monsters. If there was some way to set it to also modify the weight of monsters stored in it that'd be useful, given it'd basically enable what is functionally a pokeball or what-have-you via letting you set the modifier to zero.

If it were feasible to make the pathfinding a bit better about going up and down stairs that'd fix it too, but that's a code thing I'm unsure how to implement.

**Comment by Zeilos** [comment]
I suspect this issue is caused by misaligned stair levels. I've had this issue a few times in normal DDA play. NPCs seem smart enough to not actually go down them though. If it IS the same issue, leashing and leading won't work. As for the workaround, I've found that adding the stairs back up to the location they correspond to above lets NPCs and animals travel between the levels.

**Comment by MoonlitRiverlight** [comment]
I've had the opposite happen where when climbing Magic Schools the followers cannot climb the staircase on ground floor up. Amusingly a zombie on the level above later broke those stairs (in another school) because it heard movement and saw me below (I assume).

**Comment by chaosvolt** [comment]
Magic Schools are a Magiclysm thing, so.

**Comment by chaosvolt** [comment]
Bit belatedly, https://github.com/chaosvolt/cdda-arcana-mod/pull/275 now gives players a way around this, at least for monsters summoned from a silver glyph. Those summoned by spells still can't benefit from this as I'm 90% certain that'd make them lose track of the spell's duration.
