### ISSUE TITLE
The way item groups works in json is about to change

### ISSUE THREAD

**Issue by Light-Wave** [chaosvolt/cdda-arcana-mod#246]
[CleverRaven/Cataclysm-DDA/pull/56469](https://github.com/CleverRaven/Cataclysm-DDA/pull/56469) changes how item groups works.
Specifically, the default behaviour of item groups will be to completely overwrite existing item groups, and you will have to specify if you want to extend an existing one.
The pull request contains a script that converts from the old way of writing them to the new way.
As of writing this, the pull request is not yet merged. I just wanted to give you a heads up.

**Comment by chaosvolt** [comment]
Nice, thanks for warning me.

**Comment by chaosvolt** [comment]
Oh! One thing I noticed here: how's this work if you have a mod that wants to add items to a group that's normally defined in another mod? Normally self-copy-from breaks HARD when you try to do mod-compatibility stuff like this, and I don't see this being an exception?

**Comment by Light-Wave** [comment]
>There is currently no check that an itemgroup copies from an existing item group, so if they try to copy-from themselves, that will work right now, but if people extend copy-from for item groups it would likely fail.

>In general, that is a solution for mod load order to solve.

/ anothersimulacrum

**Comment by chaosvolt** [comment]
Yeah that's a big problem. That outright breaks an IMMENSELY useful feature. :/

**Comment by chaosvolt** [comment]
Er wait, the way he phrased it is confusing. He said self-copy-from will work, but won't if using extend? Then doesn't that mean by definition it DOESN'T work if now the only way to add new items is by extend? That's not a straight answer.

**Comment by anothersimulacrum** [comment]
If both itemgroups act as though they are extending an existing itemgroup, it will work. But if changes are made to itemgroup inheritance in the future, it would likely break, and so load order would be the appropriate way for that problem to be addressed.
