### ISSUE TITLE
Parsed vitamin overwrites existing definition

### ISSUE THREAD

**Issue by D3adDrop** [chaosvolt/cdda-arcana-mod#248]
DEBUG    : Error: Json error: data/mods/Arcana/mutations/vitamins.json:3:10: parsed vitamin overwrites existing definition

[
  {
    "id":
         ^
          "arcana_mutagen_dragonblood",
    "type": "vitamin",
    "vit_type": "counter",

 FUNCTION : bool main_menu::load_character_tab(bool)
 FILE     : src/main_menu.cpp
 LINE     : 1073
 VERSION  : f0715f7

**Comment by chaosvolt** [comment]
Delete the old folder before you update, don't just blindly copy-paste folders into each other.
