### ISSUE TITLE
Links to smf.cataclysmdda are outdated

### ISSUE THREAD

**Issue by BorkBorkGoesTheCode** [chaosvolt/cdda-arcana-mod#25]
Did a search for your forum post on discourse and found it here: 
https://discourse.cataclysmdda.org/t/dumb-mod-idea-arcana-wip/10262

**Comment by chaosvolt** [comment]
Oh right. Honestly since I don't maintain a separate dropbox repo like I started off doing, and I'm likely banned there, no real reason for me to link to the new forum. I've been meaning to update the readme, but eh. @.@
