### ISSUE TITLE
 Forgemaster3 error when adding dda patchmod for magiclysm

### ISSUE THREAD

**Issue by Maryionet** [chaosvolt/cdda-arcana-mod#256]
![Screenshot_2022-05-06-16-08-14-93_6fe8938556442e3d4f710ab4f9a16601](https://user-images.githubusercontent.com/68288642/167093687-0057670d-db5a-4610-8ffc-6303d5ef817b.jpg)

**Comment by chaosvolt** [comment]
Whoops, simple copypaste error, looks easy enough to fix.

**Comment by chaosvolt** [comment]
Thanks for finding that, do tell if anything else comes up.
