### ISSUE TITLE
Martial Arts techniques not triggering due to lack of Attack Vectors

### ISSUE THREAD

**Issue by WreckingAbandon** [chaosvolt/cdda-arcana-mod#257]
I dunno if there is already a fix underway since I can't find anybody mentioning this yet, but it is rather simple to fix, maybe just a little bit trying on the patience. Most of the attack vectors of the techniques seems to be weapons anyways.

**Comment by WreckingAbandon** [comment]
You mean the Attack Vectors? Its been on since Feb it says, saw it in Pull Request #53954.

**Comment by chaosvolt** [comment]
https://github.com/chaosvolt/cdda-arcana-mod/commit/89cfbac25c30937392219c84e11441d27dd6eee5 should fix it now, but do tell me if anything else comes up.

I do see that automatic dodge and block counters have been phased out in DDA, I'll have to mess with that later on but for now at least it evidently still has code support.

I'll also need to send Noct an update to the DDA version of Cata++

**Comment by WreckingAbandon** [comment]
I think they said they're gonna keep the code for the old counter system for now. But still, finally I can show those otherworldly monsters what-for, in style!

**Comment by chaosvolt** [comment]
Thanks, I might see about switching to more active counters but will have to see.
