### ISSUE TITLE
Anvil quality now exists, grip quality to possibly follow

### ISSUE THREAD

**Issue by smolbird** [chaosvolt/cdda-arcana-mod#26]
See pull request by @BorkBorkGoesTheCode: https://github.com/CleverRaven/Cataclysm-DDA/pull/23637

Only thing of note is that anvils are max quality at 3, with boulders and medieval-mod bronze anvils have 1 and 2, respectively. No usage in actual recipes yet, except for 2 crafting requirements.

**Comment by BorkBorkGoesTheCode** [comment]
@chaosvolt Oof?

**Comment by chaosvolt** [comment]
Much oof. Nah, just kidding. I did have some ideas for recipes that would warrant changes to use qualities but I've been lazy and haven't worked on them yet, so.

Any idea on conventions for anvils yet?

**Comment by chaosvolt** [comment]
Closed as no follow-up to changes have occurred, and anv-

FUCK I forgot to switch to using anvil quality in recipes, but I'll go ahead and do that now, which would've closed this anyway...
