### ISSUE TITLE
Error when lauching: Json Error. Game won't lauch

### ISSUE THREAD

**Issue by Dream1111150** [chaosvolt/cdda-arcana-mod#260]
![image](https://user-images.githubusercontent.com/107230307/172977565-ce2a85bc-188d-49f6-8c80-ea62a1b1a3e5.png)
![image](https://user-images.githubusercontent.com/107230307/172978044-f21899cb-6bca-4a4b-95e6-750b68ed82cc.png)
![image](https://user-images.githubusercontent.com/107230307/172977915-d06ca265-9799-4308-a1e0-febfa73e533c.png)

**Comment by Dream1111150** [comment]
Can I have some help please
I have been struggling with this for about a day, trying to fix it/understand and I can't do neither

**Comment by chaosvolt** [comment]
You're using the master branch of Arcana with 0.F stable DDA. Use the correct release for that: https://github.com/chaosvolt/cdda-arcana-mod/releases/tag/0.F-3

**Comment by Dream1111150** [comment]
thanks man, I'm so sorry. Feel so dumb now. Really thanks, making mods like that for the community is really cool and sorry again.

**Comment by chaosvolt** [comment]
No worries.
