### ISSUE TITLE
Issues regarding this or one your mods

### ISSUE THREAD

**Issue by T3hBoy** [chaosvolt/cdda-arcana-mod#268]
Hello, testing some mods with each update, mostly the ones from Kenan's modpack, and apparently he told me some of the issues come from your mods
https://github.com/Kenan2000/BrightNights-Structured-Kenan-Modpack/issues/120#issue-1330314880

**Comment by chaosvolt** [comment]
Should be fixed by this earlier: https://github.com/chaosvolt/cdda-arcana-mod/commit/96fefe3eccdda086e1536c40619c0e4b3e15c851

As well as corresponding Dorf Life fix: https://github.com/chaosvolt/Dorf-Life-CDDA/commit/a03b6e8fa57801ac2d1904ee882454b95e4760eb

**Comment by T3hBoy** [comment]
everything fixed, thanks
