### ISSUE TITLE
Candle of Warding runs out immediately

### ISSUE THREAD

**Issue by mark-ik** [chaosvolt/cdda-arcana-mod#271]
In DDA experimental build 2022-08-27-0708, lighting a candle of warding causes it to disappear. It doesn't or cannot turn into candle of warding (on). It emits no light.

You can still place the candle and it works as expected. Normal candles work as expected and consume their charges.

- OS: Windows
    - OS Version: 10.0.22621.457 (22H2)
- Game Version: aa80ff7-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Professions [package_bionic_professions],
    Arcana and Magic Items [Arcana],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Slots [cbm_slots],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Mythical Martial Arts [MMA],
    Arcana/Magiclysm Patchmod [Arcana_Magiclysm_Patch],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro]
]

Thanks!

**Comment by chaosvolt** [comment]
Uh, that's weird. Candles of warding don't HAVE charges, so unless DDA messed something up with transforming items that don't become active when changed...

Will test in a bit to see if anything changed recently.

**Comment by chaosvolt** [comment]
Ahah, cause seems to be https://github.com/CleverRaven/Cataclysm-DDA/pull/60039, adding `"ammo_scale": 0` to the action seems to fix this. I'll do that and check for any other items that require this.

**Comment by chaosvolt** [comment]
Fixed by https://github.com/chaosvolt/cdda-arcana-mod/commit/b2e913de8c9f23258a64b7f292e63bb8ab98ba99
