### ISSUE TITLE
"Json loading from efficient binary representation for performance wins" PR broke mod_tilesets in DDA version

### ISSUE THREAD

**Issue by chaosvolt** [chaosvolt/cdda-arcana-mod#277]
Opening this issue to track it and to ask the relevant PR author if they know of the likely cause. @akrieger, @anothersimulacrum as they were involved in another tileset-breakage update a while back and might have an idea as to the cause. ~~Possibly an old PR first opened in PR may have introduced regressions and broke https://github.com/CleverRaven/Cataclysm-DDA/pull/49436?~~ I don't SEE anything that looks like an obvious regression in the file changes for mod_tilset.cpp so that likely isn't it, but can't tell.

It's been confirmed that https://github.com/CleverRaven/Cataclysm-DDA/pull/50143 seems to be the cause of this error when attempting to load mods that contain a mod tileset:
```
 DEBUG    : Error: Failed to open tile info json: data/mods/Arcana/mod_tileset/mod_tileset_Ultica_large.json

 FUNCTION : new_character_tab
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\main_menu.cpp
 LINE     : 947
 VERSION  : a3c6a29
```

The build prior to https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2022-09-17-1634 has no such errors, while this build an onward does.

The irksome thing is, I'm looking at this and can't for the life of me see what could cause this. For example, this in-repo mod tileset loads just fine:
```
  {
    "type": "mod_tileset",
    "compatibility": [ "HitButton_iso" ],
    "tiles-new": [
      { "file": "sees_player_hitbutton_green.png", "tiles": [ { "id": "overlay_friendly_sees_player", "fg": 0 } ] },
      { "file": "sees_player_hitbutton_yellow.png", "tiles": [ { "id": "overlay_neutral_sees_player", "fg": 1 } ] },
      { "file": "sees_player_hitbutton_red.png", "tiles": [ { "id": "overlay_hostile_sees_player", "fg": 2 } ] },
      { "file": "sees_player_hitbutton_pink.png", "tiles": [ { "id": "overlay_other_sees_player", "fg": 3 } ] }
    ]
  }
```

While this for example in Arcana does not work:
```
  {
    "type": "mod_tileset",
    "compatibility": [ "UltimateCataclysm", "UltimateCataclysmDemo" ],
    "tiles-new": [
      {
        "file": "mod_tileset/arcana_expan_ultica_normal.png",
        "tiles": [
          { "id": "satchel_eternity", "fg": 0 },
          { "id": "thunder_sigil", "fg": 1 },
          { "id": "bloodscourge", "fg": 2 },
          { "id": "hand_of_armok", "fg": 3 },
          { "id": "scourge_staff", "fg": 4 },
          { "id": "sun_sword", "fg": 5 },
          { "id": "staff_druidic", "fg": 6 },
          { "id": "verge_meteoric", "fg": 7 },
          { "id": "f_blade_upright", "fg": 8 },
          { "id": "ethereal_crossbow", "fg": 9 },
          { "id": "hexenhammer", "fg": 10 },
          { "id": "fd_veil_light", "fg": 11 },
          { "id": "tr_portal_crystallized", "fg": 12 }
        ],
        "sprite_width": 32,
        "sprite_height": 32
      }
    ]
  }
```

I've tried the following obvious answers:
1. Moving all `tiles` sections from separate files to a single one, like in the two mod tilesets present in DDA.
2. Moving the relevant files out of the mod_tileset subfolder and into the main folder, like where the in-repo tileset mods have their files.
3. Shaving `compatibility` down to only a single tileset.
4. Removing the UDP mod_tileset files to test only mod tileset files that have an actual in-repo tileset present.
5. Testing only the "normal" size Ultica compatibility file, also removing `sprite_width` and `sprite_height`.

None of those have changed the results.

**Comment by akrieger** [comment]
Not sure but I'll check it out as soon as I can.

**Comment by chaosvolt** [comment]
I'm looking at the PR's file changes and don't see any obvious regressions introduced by it, and just in case testing a few more adjacent builds to make absolutely sure it's this one, but none of the other PRs shown on releases seem to touch tileset stuff far as I can tell.

**Comment by chaosvolt** [comment]
Ahah! I finally got something useful out of my testing:
```
 DEBUG    : Error: Failed to open tile info json: data/mods/sees_player_retro/mod_tileset.json

 FUNCTION : new_character_tab
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\main_menu.cpp
 LINE     : 947
 VERSION  : a3c6a29
```
So, one of the things that was stumping me was how just copying the in-repo tileset stuff wasn't triggering the error despite no visible difference in the JSON. So after a bit more I realized I had the tileset set to Ultica.

So when I set the tileset to Retrodays and use the `sees_player_retro` in-repo mod, the error above triggers. Can't test with `sees_player_hitbutton` as Hitbutton tileset is no longer in the repo. But this confirms it's not anything specific to third-party mod_tileset JSON.

Definitely would be worth opening an issue in DDA's repo if no one else has yet, now that there's a confirmed way to get this to happen using an in-repo mod_tileset.

**Comment by akrieger** [comment]
Ahhh it's a one character typo. Putting up a fix now.

**Comment by akrieger** [comment]
Thanks for the detailed repro instructions - made it pretty trivial to track down!

**Comment by chaosvolt** [comment]
Nice, glad to see that turned out to be an easy fix, and thank you. Will go ahead and close this now probably, since don't think a PR can close an issue in a separate repo.
