### ISSUE TITLE
Last experimental change ids

### ISSUE THREAD

**Issue by KymasTuran** [chaosvolt/cdda-arcana-mod#279]
The best loot come from portal storms, They change all the IDs of these mons or remove them, there is no loot now.

**Comment by chaosvolt** [comment]
Uh, what do you mean.

**Comment by KymasTuran** [comment]
Sorry for my english. Is better if I just paste it:
https://github.com/CleverRaven/Cataclysm-DDA/pull/60788

**Comment by chaosvolt** [comment]
Oh, some new monsters I could add monsterdrops to? Can mess with that later on, yeah.

**Comment by KymasTuran** [comment]
I know this is not the right place to ask (need another post I guess) but:
Can you add some way to protect or purge against the ludicrous level of fatigue the monster attacks add in the portal dungeon? Last time mine was above 10k, sleep for days and died several times, finally I edit to continue playing. You got "citrine incense" but barely remove 24 :p

**Comment by chaosvolt** [comment]
>10 thousand fatigue

Yeah that's absolutely fucked, I'll have to see how it's applied. If it's effect-based then it's easy to make stuff like Ward Against Evil halt it, if it's EoC stuff then it'll be harder. And if it's just a `recover_energy` spell like a fresh new incarnation of the mi-go slaver beam bullshit then it's basically impossible to hack around...

**Comment by KymasTuran** [comment]
If I can help in any way just ask. I made some crude edits an upload some json files in the past and recently fix the artifact spell HEAL that actually need negative numbers. Not a coder (work in the same stuff that Willy from the Simpsons, janitor in school) but I try my best.

**Comment by chaosvolt** [comment]
No worries, just gotta find time to mess with it.

**Comment by KymasTuran** [comment]
I just close to not clutter your list. Not fully aware you dont do it. :p 
I stop entering the portal storm dungeon long ago, too dangerous. I edit the incense to remove 600 fatigue but is untested. And heal spell to heal animals.
Your mod is awesome an as a permanent place in my load list.
Want this reopen?

**Comment by chaosvolt** [comment]
No worries, reopen it if you're like, just gotta set aside time to work on it when I can.
