### ISSUE TITLE
How can I download BN version in mobile?

### ISSUE THREAD

**Issue by Burntman** [chaosvolt/cdda-arcana-mod#281]
I'm sorry to bother you but I'm first time to use github and I can't find it, is there 
any way to download it in mobile?

**Comment by chaosvolt** [comment]
It should be doable but I've never tried for myself, as don't have the sort of phone that could do so.

**Comment by Nightrealm** [comment]
it should be the same as on the computer but some phones hide the data to add or access the files to the game.
so you need an app like zarchiver to access it, then put the files in the, 
android/data/com.cataclysmbnteam.cataclysmbn.experimental/files/data/mods.
