### ISSUE TITLE
I CANT MAKE THIS MOD WORK WITH ANYTHING

### ISSUE THREAD

**Issue by morgoth91** [chaosvolt/cdda-arcana-mod#282]
i get nothing but errors everytime  i put this mod in  the list and i dont know what the hell to do about it. any of you computer wizards can help??

 DEBUG    : Error: Json error: data/mods/Arcana/flags.json:6:5: missing required field "context" in object: {
    "id": "arcana_birchbark_weave",
    "type": "json_flag",
    "info": "This gear has been altered by druidic magic, increasing its <good>protection</good>."
  },

    "type": "json_flag",
    "info": "This gear has been altered by druidic magic, increasing its <good>protection</good>."
  },
    ^
  {
    "id": "arcana_tanbark_weave",
    "type": "json_flag",

 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 865
 VERSION  : 0.F-2

**Comment by chaosvolt** [comment]
I really need to make a "did not read the readme" label for this kind of issue given how many times I've seen this reported. You're using the master branch of the mod, intended for recent experimental builds, with the 0.F stable release of DDA. An outdated VERSION of 0.F stable at that, that's a new one.

Here. If it still doesn't work it's likely due to differences between 0.F-2 and 0.F-3: https://github.com/chaosvolt/cdda-arcana-mod/releases/tag/0.F-3

**Comment by morgoth91** [comment]
I keep getting this error everytime..even with the right mod

 DEBUG    : (json-error)
Json error: data/json/mutations/mutations/mutations_dragonblood.json:594:17: Invalid or misplaced field name "body_size" in JSON data

    "movecost_obstacle_modifier": 1.1,
    "flags": [ "PRED4" ],
    "body_size":
                ^
                 "LARGE"
  }
]


 FUNCTION : void JsonObject::report_unvisited() const
 FILE     : src/json.cpp
 LINE     : 122
 VERSION  : 0.F-2

**Comment by morgoth91** [comment]
any ways i can fix this? really wanna play with this mod... magiclysm leaves a lot to be desired..

**Comment by chaosvolt** [comment]
Use the Arcana folder that's in it, not the Arcana_BN folder.

**Comment by morgoth91** [comment]
i just went ahead and downloaded the experimental version to use the first one instead...sorry for causing you frustration lol, and good job on this mod btw, its one of the best mods out there.

**Comment by chaosvolt** [comment]
Thanks, glad it works now at least. ^^"
