### ISSUE TITLE
Tempered weaponry not working with Via Gladeo et Malleo

### ISSUE THREAD

**Issue by WreckingAbandon** [chaosvolt/cdda-arcana-mod#283]
Tempered arming sword and the like should be useable in the MA.

On another note. Tempered incorruptible sword anyone?

**Comment by chaosvolt** [comment]
I'll have to look and see how many new minor flavor variations of the same item they've gone and added now, then add them to the martial art.

Probably also update the recipe for incorruptible sword too, right now it's generic and implied to be a modification of any of several similar types of sword, so just making sure its stats are reasonably an average of the available weapons used to make it should be adequate for the time being.

**Comment by chaosvolt** [comment]
Oh this is gonna be FUN.
![image](https://user-images.githubusercontent.com/11582235/193265101-48921055-1b8c-4e2d-92ac-9ba37a342cc3.png)
