### ISSUE TITLE
Hunter visor is not working?

### ISSUE THREAD

**Issue by YuPro** [chaosvolt/cdda-arcana-mod#289]
Looks like IR vision is not working because of blindness. At least in my game activated visor works like blindfold with hear protection (and flash protection, but I don't think it's matters when you're blind).

Or I just don't understand something?

**Comment by chaosvolt** [comment]
The clairvoyance should be working at least, unless DDA broke something.

**Comment by YuPro** [comment]
![2022-10-07_18-30-02](https://user-images.githubusercontent.com/23240052/194596241-efd20cca-3161-490f-b85f-912eb33bc39a.png)
![2022-10-07_18-30-27](https://user-images.githubusercontent.com/23240052/194596289-57826c75-2969-4917-bf6f-59617d3c4743.png)
![2022-10-07_18-31-09](https://user-images.githubusercontent.com/23240052/194596331-8c5657b4-864e-4da6-bba0-5c43195e45a5.png)

**Modlist:**
> [
>   "dda",
>   "no_npc_food",
>   "no_fungal_growth",
>   "package_bionic_professions",
>   "secronom",
>   "aftershock",
>   "Arcana",
>   "Cata++",
>   "magiclysm",
>   "xedra_evolved",
>   "MST_Extra",
>   "DinoMod",
>   "World_on_fire",
>   "extra_mut_scens",
>   "translate_dialogue",
>   "Dorf_Life",
>   "Tankmod_Revived",
>   "Arcana_aftershock_Patch",
>   "Arcana_Cata++_Patch",
>   "Arcana_Dinomod_Patch",
>   "Arcana_Magiclysm_Patch",
>   "Graphical_Overmap_SDG_Arcana",
>   "Graphical_Overmap_SDG_Cata++",
>   "Graphical_Overmap_SDG_secronom",
>   "Graphical_Overmap_SDG",
>   "sees_player_retro",
>   "sees_player_hitbutton",
>   "alt_map_key"
> ]

**Comment by chaosvolt** [comment]
Oh god fucking damnit they really did break it.

**Comment by chaosvolt** [comment]
Okay, no. It's not that. I tested removing the `BLIND` flag from the active mask of insight:
![image](https://user-images.githubusercontent.com/11582235/195154538-768dfa70-be67-41c5-b6ae-1f86feeea696.png)

You need to go open an issue for it: https://github.com/CleverRaven/Cataclysm-DDA/issues\

The issue is a DDA one, not an Arcana one, some code change has straight-up broke clairvoyance outright.

**Comment by chaosvolt** [comment]
To clarify further: mutations with the `SUPER_CLAIRVOYANCE` flag (as given by the debug clairvoyance artifact) work, as does the regular `CLAIRVOYANCE` flag as can be verified by casting Magic Sign: Clairvoyance. But the `CLAIRVOYANCE_PLUS` flag no longer works, that's the one mask of insight was using.

**Comment by chaosvolt** [comment]
Wait, that's odd...granting the mutation Debug Clairvoyance, the version that has the `CLAIRVOYANCE_PLUS` flag, works fine. But not the version used by the mask of insight. Uh...

**Comment by chaosvolt** [comment]
AHAH! For whatever reason, having it defined as an actual enchantment via `passive_effects` is broken. But when I convert the enchantment's effects entirely into being defined within relic_data, it works.

**Comment by YuPro** [comment]
Ok, it's only Hunter's Visor that's not working, Mask is OK. will look what is missing now.

**Comment by chaosvolt** [comment]
Old versions of the item will still have the old broken enchantment, did you try spawning in a new hunter's visor?

**Comment by YuPro** [comment]
Thanks, it worked.

Game cashes that kind of things? Interesting mechanics decision, do you know if it's to be more save-compatible?
