### ISSUE TITLE
How to charge my essence bionic?

### ISSUE THREAD

**Issue by WreckingAbandon** [chaosvolt/cdda-arcana-mod#297]
I dunno how. Last time I checked they have a refueling option when you're in the bionic menu after they did away with basically eating it. I can't open said refueling option, its not in keybindings anywhere. Now even the Battery CBM has a sort of clothing on you where you can store a battery in.

EDIT: Maybe #61049 something to do with it? Everything gets a pseudo item now which can be reloaded with their fuel stuff. The ability to consume their fuel source probably was removed after this. That or I'm just dumb/blind since I can't figure out how to refuel the essence CBM.

**Comment by chaosvolt** [comment]
Yep, looks like they messed with it again. Oh wow, they even removed the ability for NPCs to use those bionics from the look of it, nice. I'll have to mess with fixing this later today, as about to be out and about.

**Comment by chaosvolt** [comment]
Was able to get some time while getting ready to tackle this, I'll still want to chuck an update at Cata++ too.
