### ISSUE TITLE
Hermit earned trust 2 no value constraint found

### ISSUE THREAD

**Issue by Milestones1** [chaosvolt/cdda-arcana-mod#306]
![Screenshot_20221219_101505](https://user-images.githubusercontent.com/120998337/208337764-0332cb0a-45fd-458f-a021-a12e0f95d516.jpg)

This is mobile unstable version dda it is the latest version, I can't seem to fix this problem It won't allow me to get in the world as I would get kicked out after this report.

**Comment by chaosvolt** [comment]
You're using the BN version of Arcana, not the DDA version. Drop the correct folder into your mods folder.
