### ISSUE TITLE
the latest mutation update breaks mod

### ISSUE THREAD

**Issue by shivachirr** [chaosvolt/cdda-arcana-mod#31]
so with the latest update it broke the mod giving me this error. i would fix it my self but im no expert coder and dont know where to look for what changed to cause this.

> DEBUG	: error: data/mods/Arcana/mutation_category.json: line 2:3: member bot found: threshold_mut
[
   {
    ^
     "id: "mutation_veil:,
     "type': "mutation_category",
Function : bool main_menu::load_character_tab()
file	 : src/main_menu.cpp
line	 : 883

>

**Comment by shivachirr** [comment]
so i was able to get it fixed by adding "threshold_mut" : "", to every mutation on the list but it now says

![debug](https://user-images.githubusercontent.com/9361172/43579048-caf90538-961e-11e8-93be-83c68f7ff2b9.png)

**Comment by chaosvolt** [comment]
Ack. I was going to fix that yesterday but some things came up.

https://github.com/chaosvolt/cdda-arcana-mod/pull/32 should fix it, thanks to @ZhilkinSerg for that.

**Comment by shivachirr** [comment]
dose not seem to help in the end unless im missing something like i said not an well even average coder and i dont really know the games code well yet

**Comment by shivachirr** [comment]
never mind its the mutation changes mod breaking it now saw yours updated now if only that one i knew how to update it has somethingt to do with the items tho

**Comment by chaosvolt** [comment]
Ah. So it is fixed for this now?

**Comment by shivachirr** [comment]
yeah arcae is good now just other mods are taking a bit longer but i manage to get them working atleast to a point

**Comment by chaosvolt** [comment]
Alright, feel free to tell me if anything else comes up.
