### ISSUE TITLE
Error at charector craition

### ISSUE THREAD

**Issue by gados1** [chaosvolt/cdda-arcana-mod#310]
DEBUG    : Error: Json error: mods/Arcana/vehicleparts.json:66:30: invalid quantity string: unknown unit

    "durability": 150,
    "power": 200000,
    "energy_consumption": "100
                             ^
                               kW",
    "breaks_into": [
      { "item": "scrap", "count": [ 1, 4 ] },

 FUNCTION : new_character_tab
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\main_menu.cpp
 LINE     : 947
 VERSION  : c12b0ce

Only mods i have activ is 
DDA
Arcana

Wtd

**Comment by chaosvolt** [comment]
Uh. Figured it out, or...?
