### ISSUE TITLE
[DDA] Duplicate entry in "stormbringer"

### ISSUE THREAD

**Issue by nemesis688** [chaosvolt/cdda-arcana-mod#315]
The recent merge added  "material": [ "qt_steel" ] at 2,472: instead of replacing the 'steel' with 'qt_steel' at line 2462

 DEBUG    : Error: Json error: S:/Games/Cataclysm DDA/dda/userdata/mods/Arcana/items/tools.json:2,472:16: duplicate entry in json object

    "bashing": 15,
    "cutting": 41,
    "material":
               ^
                [ "qt_steel" ],
    "color": "dark_gray",
    "pocket_data": [ { "pocket_type": "MAGAZINE", "rigid": true, "ammo_restriction": { "essence_blood_type": 9 } } ],

 FUNCTION : new_character_tab
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\main_menu.cpp
 LINE     : 986
 VERSION  : e24ee5e

**Comment by chaosvolt** [comment]
Hecc, easy fix at least.
