### ISSUE TITLE
mapgen_varients church_3rdfloor_1 is rotated 180 degrees

### ISSUE THREAD

**Issue by RAldrich** [chaosvolt/cdda-arcana-mod#319]
Simple mapgen error - church_3rdfloor_1 is incorrectly rotated 180 degrees: stair connections work, but it floats in the air / has no ceiling because it ends up oriented 180 degrees from the rest of the building. I fixed it by updating rows, but I keep forgetting to submit a PR for this and am now going to be away from my dev machine for several weeks, so I figured I'd report it while I'm thinking about it:

https://github.com/chaosvolt/cdda-arcana-mod/blob/master/Arcana/overmap_and_mapgen/mapgen_variants.json#L391-L416

Easy to reproduce / test by spawning the building in debug mode.

**Comment by chaosvolt** [comment]
Ah, weird. Will see if I can tackle this later tonight or tomorrow.

**Comment by chaosvolt** [comment]
Finally got to look at this and...yep, for some wacky reason they flipped it around at some point.

Compare BN: https://github.com/cataclysmbnteam/Cataclysm-BN/blob/upload/data/json/mapgen/church.json#L359
Vs. DDA: https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/mapgen/church.json#L318
