### ISSUE TITLE
Can't start up game with arcana enabled on the newest experimental 

### ISSUE THREAD

**Issue by Beans142** [chaosvolt/cdda-arcana-mod#320]
Hello after updating to version 79a4e9f  I've been unable to play with the arcana mod in both old and new saves 
I get the following error after which the save boots me to the main menu.
  DEBUG    : Error: Json error: data/mods/cdda-arcana-mod-master/Arcana/materials.json:19:29: Expected a string, got a 1

    "bash_dmg_verb": "damaged",
    "cut_dmg_verb": "damaged",
    "fuel_data": { "energy":
                            ^
                             1 }
  },
  {

 FUNCTION : bool main_menu::load_game(const string&, const save_t&)
 FILE     : src/main_menu.cpp
 LINE     : 1038
 VERSION  : 79a4e9f

[debug.log](https://github.com/chaosvolt/cdda-arcana-mod/files/10828949/debug.log)

**Comment by chaosvolt** [comment]
Did you make sure you're actually using the master branch of Arcana, and not any of the releases?
![image](https://user-images.githubusercontent.com/11582235/221309208-0bb8c991-b2e9-472c-8d9c-be2a5cb7d2f6.png)

**Comment by Beans142** [comment]
Yes ,Yes i did .Here's an image of it in the mods folder
![MODS](https://user-images.githubusercontent.com/109043884/221313229-951a47f1-cd6f-4127-9158-76d35c8d5545.PNG)

**Comment by chaosvolt** [comment]
Well for one, you dumped the wrong folder in there. Make sure it's just the `Arcana` folder, not the entire repo's folder.

**Comment by Beans142** [comment]
First that shouldn't affect it cause it worked just fine before updating, but sure i've extracted the arcana folder to the main mods one as well as the patchmods and it still gives me the same error.

**Comment by Beans142** [comment]
Ok i think i've found the issue .For some reason when i download the master repo the materials file doesn't have the energy paramater thingy set to kj which apparently confuses the game since it expects units for the energy (i think) and shuts down the save

**Comment by Beans142** [comment]
Yup changing the energy parameters to the ones in the github repo fixed it .

**Comment by chaosvolt** [comment]
> First that shouldn't affect it cause it worked just fine before updating, but sure i've extracted the arcana folder to the main mods one as well as the patchmods and it still gives me the same error.

It will break the hell out of things because the folders include both the DDA version of the mod AND the BN version.

> Ok i think i've found the issue .For some reason when i download the master repo the materials file doesn't have the energy paramater thingy set to kj which apparently confuses the game since it expects units for the energy (i think) and shuts down the save

You had an older version, likely one of the releases, kicking around in there. :V
