### ISSUE TITLE
displacemeng surge and distortion amplifier motors case deafness

### ISSUE THREAD

**Issue by NegInfinity** [chaosvolt/cdda-arcana-mod#324]
Well, this is a new one.

Installing a displacement surge motor or distortion amplifier motor onto a truck make player and npcs deaf when engine is started or running. My cdda version is experimental, `d9e21d8`, and I do not recall having this problem before. Arcana version is `1db34c4`. Updating arcana to `7d375ec36` did not fix the problem. 

Starting and toggling those engines seem to take a lot of time as well, basically if you make a mistake of toggling the engine while moving 6 km/h forward (a very common situation), you'll crash into a wall or tree and smash the truck into pieces.

Looking at the engine stats, there seem to be more zeroes in engine power than before, perhaps this has something to do with the problem. At the moment, both engines have power of 200 000 000, which is way more than any other engine in the game.

**Comment by chaosvolt** [comment]
Huh, it's supposed to be 200,000 if I recall, did something mess up with DDA's units? :/

**Comment by chaosvolt** [comment]
Ahah, looks like they switched to power values in strings, so they most likely bricked the old integer values by a factor of a thousand in the process.

**Comment by chaosvolt** [comment]
Ahah, energy consumption had been converted to string units but power and epower was only converted recently by https://github.com/CleverRaven/Cataclysm-DDA/pull/61950

This also means I'll have to set aside a 0.G release of the DDA version of Arcana since that PR didn't make it into 0.G.
