### ISSUE TITLE
[DDA] "UNARMED_WEAPON" Flag has been removed.

### ISSUE THREAD

**Issue by nemesis688** [chaosvolt/cdda-arcana-mod#327]
This pull is the one that eventually moved the flag to an obsolete file:

https://github.com/CleverRaven/Cataclysm-DDA/pull/62578

And this more recent one seemed to have remove (and reconfigured) said obsolete file.

https://github.com/CleverRaven/Cataclysm-DDA/pull/64399

**Comment by chaosvolt** [comment]
Looks like https://github.com/chaosvolt/cdda-arcana-mod/pull/328 should fix it.
