### ISSUE TITLE
Bionic-related debugmsg

### ISSUE THREAD

**Issue by Kromgart** [chaosvolt/cdda-arcana-mod#332]
A recent bionic-power-related [PR #63978](https://github.com/CleverRaven/Cataclysm-DDA/pull/63978) added this block into src/bionics.cpp:

```C++
if( has_flag( json_flag_BIONIC_GUN ) && power_activate != 0_kJ ) {
    debugmsg( "Bionic %s attribute power_activate is ignored due to BIONIC_GUN flag.", id.c_str() );
}
```

When loading the game with Arcana it is executed and throws warnings for bio_electrothermal_arc_projector and bio_rift_focus_projector. I don't really know yet how these are supposed to work, so can't make a PR myself.

**Comment by Hirmuolio** [comment]
Remove `"act_cost": "80 kJ"` from the bionics.  
Add `"energy_drain": "80 kJ"` and `"USES_BIONIC_POWER"` flag to the gun that the bionic fires.
