### ISSUE TITLE
Arcana gun UPS mods not working.

### ISSUE THREAD

**Issue by WreckingAbandon** [chaosvolt/cdda-arcana-mod#334]
Everytime I try to fire it it tells me that it needs at least X amounts of charges, but I have a UPS cbm installed and the power is sufficient, tried it with a regular UPS device and it still doesn't fire.

**Comment by chaosvolt** [comment]
Are you using the latest experimental for both, or stable release with stable DDA?

**Comment by WreckingAbandon** [comment]
I managed to get it working by adding the "USE_UPS" flag to the gunmods, which is weird since I remember it working before, guess the flag is a new thing?

**Comment by chaosvolt** [comment]
Ah, looks like I forgot that. Can fix in a sec.

**Comment by WreckingAbandon** [comment]
Wow that was quick, thanks!

**Comment by chaosvolt** [comment]
https://github.com/chaosvolt/cdda-arcana-mod/commit/83897e98279edf1c6e42f249204c4d815fedf87a should hopefully fix it. And happened to be online working on something at the time so. ^^"
