### ISSUE TITLE
Sanctified Bone Charm Low Max Charges

### ISSUE THREAD

**Issue by KoRv117** [chaosvolt/cdda-arcana-mod#336]
The Sanctified Bone Charm only has 10 max charges but requires 20 to be used, I crafted the quickened stinger flute to test another item like that and it has 200 max while needing 40 to use, so im guessing the sanctified bone charm is supposed to have 100 max charges?

**Comment by chaosvolt** [comment]
Whoops, thanks for spotting that.

**Comment by KoRv117** [comment]
no prob, figured it was just a typo
