### ISSUE TITLE
i guess material repair needs tweaking according to 65846

### ISSUE THREAD

**Issue by alp7292** [chaosvolt/cdda-arcana-mod#351]
https://github.com/CleverRaven/Cataclysm-DDA/pull/65846

**Comment by chaosvolt** [comment]
Hecc, will fix it in a bit.

**Comment by chaosvolt** [comment]
No load errors, looks like `repairs_like` is used differently and not strictly needed as much anymore but still usable, so only thing that will need doing is specifying repair difficulty for the like one or two materials in Arcana that don't copy from another material.

**Comment by chaosvolt** [comment]
https://github.com/chaosvolt/cdda-arcana-mod/commit/6a8e07f3e454834431841f23a456e8c6c777a6cc should address that main point about some items potentially having a material that lacks a repair difficulty, most of the rest should be covered by copy-from and retaining repairs like.
