### ISSUE TITLE
mapgen_hermitage

### ISSUE THREAD

**Issue by TadhgEomonn** [chaosvolt/cdda-arcana-mod#352]
Starting new game with the latest CDDA version (2023-06-23-2029) and most recent version of Arcana outputs this error and then jumps back to start screen.

 DEBUG    : Error: Json error: data/mods/Arcana/overmap_and_mapgen/mapgen_hermitage.json:154:14: format: rows: row 4 column 4: '2' is not in 'terrain', and no 'fill_ter' is set!

    "weight": 300,
    "object": {
      "rows":
             ^
              [
        "                        ",
        "                        ",

 FUNCTION : new_character_tab
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\main_menu.cpp
 LINE     : 983
 VERSION  : 720adec

**Comment by chaosvolt** [comment]
Nice, easy fix it looks like.
