### ISSUE TITLE
Invalid special_attack

### ISSUE THREAD

**Issue by waveyl** [chaosvolt/cdda-arcana-mod#353]
![image](https://github.com/chaosvolt/cdda-arcana-mod/assets/22638873/8205aacf-3a32-40b9-82e6-97308cb31122)
![image](https://github.com/chaosvolt/cdda-arcana-mod/assets/22638873/f860d7cb-b013-4451-a83b-d90595ad0be7)
![image](https://github.com/chaosvolt/cdda-arcana-mod/assets/22638873/15d060ff-aa79-495d-8778-58a80ceed400)
![image](https://github.com/chaosvolt/cdda-arcana-mod/assets/22638873/c834d5f4-5ab1-4c39-918a-8f5f60e86a65)

**Comment by chaosvolt** [comment]
You're using a modpack version, not the actual source. All but the first error are things already fixed, I'll look into the first one however.

**Comment by chaosvolt** [comment]
On top of that, I just discovered while testing the monster attack fix that latest version of DDA is prone at present to segfaulting at random right now. I might suggest Bright Nights.

**Comment by chaosvolt** [comment]
Fixed by https://github.com/chaosvolt/cdda-arcana-mod/commit/8b35544301c9752878b149c3b6bcc508b222ab41
