### ISSUE TITLE
What is the intended calorie intake for a full Dragonblood? And Dragonblood Threshold not working.

### ISSUE THREAD

**Issue by Celepito** [chaosvolt/cdda-arcana-mod#355]
Heya, me again with another pair of issues.

The day after getting all the DB mutations, I did a day of blacksmithing, specifically a bunch of pipe fittings. Moderate Activity, and my Weariness never dropped into a level where I would have gotten a malus. 

But since then, I've basically only been eating. Tracking it with the in-game smartphone tracker, I've consumed 38k kcal day 1, 35k day 2, 25k day 3 and am still getting the message that I should consume more calories. And I dont know if that is intentional, having to consume upwards of 100k kcal in 3 days, so I thought I'd ask? Like, it doesnt seem intentional, because I was eating ~8k kcal on active days before, and from reading the code it should only be 70% more, not whatever this is. I've basically gone through my whole stockpile of food, and I've not even gotten to overweight.

And if its indeed intentional, might I suggest a reduction? Because how are you supposed to sustain that in the slightest? Though, again, I dont get how I have that much calorie requirement in the first place (since I'm still getting told to eat more).

Checking with the debug menu, I do have 184k kcal stored, so I really dont know what is going on here.

Looking via the "Check Game State", yeah, seems the base metabolic rate with all the Inner Fire mutations is 10k kcal a day (10168, to be exact), so that actually does seem in line with everything. So this just gets back to the question if that high is intended or not. (And now it shows the metabolic rate as 5960, I dont fucking know anymore. Guess is calculates that based on activity?)

Asking on the CDDA discord, the weight/BMI system seems to be fucky when you get real tall (likely just over 200cm, with Monsterous Form increasing my size to 250cm), so I dont think its an issue specifically to this mod. Ergo, this part can be considered solved, sorry about that.

Somewhat related, there seems to be an issue with the Dragonblood Threshold mutation? I had gained every pre-threshold mutation, and spend 150 blood essence (so 15 tries) without gaining the Threshold (but getting a ton of the "Yearning to be free" messages), at which point I gave it myself with the debug menu. Potentially related to the mutation changes? Since you need a IIRC the serums now to gain a threshold, or something along those lines, so that might interfere somewhere.

**Comment by Celepito** [comment]
As the main issue is a main game problem, I'll close this.

**Comment by chaosvolt** [comment]
Whoops, sorry for not noticing this, things have been very busy as of late. I'll have to test whether there's something wrong with the threshold itself, it relies on different EoC logic than vanilla mutations specifically to avoid the fuckiness with the mutagen vitamin stuff.

Metabolism changes definitely sound like a bug on DDA's end however.
