### ISSUE TITLE
DDA Content Update Breaks / Changes Charge Using Comestibles

### ISSUE THREAD

**Issue by b3brodie** [chaosvolt/cdda-arcana-mod#358]
Loading a world with Arcana installed yields the following error:

 DEBUG    : warnings for type red_black_vulnerary:
charges defined but can not have any

 FUNCTION : check_definitions
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\item_factory.cpp
 LINE     : 2390
 VERSION  : f402277

Likely due to this change:
https://github.com/CleverRaven/Cataclysm-DDA/pull/60885

**Comment by chaosvolt** [comment]
Oh that's cool, totally not going to break basically every mod and warrant lots of tweaks to items and itemgroups for reasons that boil down to nested containers still acting weird 3 years later...I'll work on it in a bit I guess.

**Comment by Snaaty** [comment]
Yeah, really irritating to see people actively the gameplay experience and only refer to other people who are then supposed to finish the mess they started? 
Anyway, thanks for your continued effort and your awesome mods, chaosvolt.

**Comment by chaosvolt** [comment]
Thanks, I'm gonna need to check the other mods I'm involved in maintaining in a bit but blargh, been busy a lot lately.
