### ISSUE TITLE
i have found a bug when creating character in a new world #idontknowwhatiamdoindood

### ISSUE THREAD

**Issue by JosephDragoUwU** [chaosvolt/cdda-arcana-mod#361]
DEBUG    : Error: Json error: data/mods/Arcana/materials.json:1:2: missing mandatory member "bash_resist"

[
 ^
  {
    "type": "material",
    "id": "essencemat",

 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 986
 VERSION  : d6ec466

idk how github worls, i thought i was suposed to report this error here so there it is, anywho i dont know if anyone gonna read this any time soon, so i am just gonna try erasing the file realted to this error as a temp fix as always, anywho bye  bye good night
oh yeh, have to say this to, i am using 0-g version of cdda, if thats helpful

**Comment by chaosvolt** [comment]
Are you using the 0.G stable release of Arcana? https://github.com/chaosvolt/cdda-arcana-mod/releases/tag/0.G

If you're using the latest experimental version from the main page a lot of things will break.

**Comment by JosephDragoUwU** [comment]
> Are you using the 0.G stable release of Arcana? https://github.com/chaosvolt/cdda-arcana-mod/releases/tag/0.G
> 
> If you're using the latest experimental version from the main page a lot of things will break.

i did download that stable released if i rememebr correctly, but i just downloaded it again using your link and it worked just fine, tyvm sir

**Comment by chaosvolt** [comment]
Huh, weird. Glad it works now at least. ^^"
