### ISSUE TITLE
itemgroup entry for spawning item X defined charges but can't have any

### ISSUE THREAD

**Issue by waveyl** [chaosvolt/cdda-arcana-mod#362]
See https://github.com/CleverRaven/Cataclysm-DDA/pull/67410

List of X:
bandolier_shotgun
chitin_piece
meat_frond
leech_flower
meat_bark
veggy_tainted
veggy
red_black_vulnerary
yellow_white_incense
e_scrap
red_black_vulnerary
yellow_white_incense
meat_pickled
meat_smoked
jerky
sausage
sausage_wasteland
cracklins
tallow
lard
cured_pelt
cured_hide
bone
leather
salt

**Comment by chaosvolt** [comment]
Shit, this is probably going to affect multiple mods in fact, been busy last couple days.
