### ISSUE TITLE
FR: Hot Dragon Chicks (Lewd)

### ISSUE THREAD

**Issue by foulman** [chaosvolt/cdda-arcana-mod#363]
That got your attention didn't it?

Can't believe you're still doing this! 😄

**Comment by chaosvolt** [comment]
Nerd. :V

I am indeed, though my DDA version is out of date since they broke charges behavior yet again in ways that I'll likely need to fix for all my mods I'm involved in, and too much IRL stuff going on to want to fuck with that.
