### ISSUE TITLE
uses undefined flag 'NON-FOULING'

### ISSUE THREAD

**Issue by waveyl** [chaosvolt/cdda-arcana-mod#368]
![image](https://github.com/chaosvolt/cdda-arcana-mod/assets/22638873/cedb365e-d223-41b5-9ec1-e952e43a7300)
Used in Arcana and Cata++

**Comment by chaosvolt** [comment]
Also chucked a Cata++ at Noct: https://github.com/Noctifer-de-Mortem/nocts_cata_mod/pull/559
