### ISSUE TITLE
Game crashing when I try to read a spellcraft scroll

### ISSUE THREAD

**Issue by Luckspeare** [chaosvolt/cdda-arcana-mod#37]
When I try to (a)ctivate a spellcraft scroll (overgrowth), the game instantly closes out.  When I try to (a)ctivate a spellcraft scroll (flame armor), it crashes, but it comes up with the submit-crash-data-to-Microsoft dialog.

I'm using the latest experimental builds, with the following mods:
[
  "dda",
  "Urban_Development",
  "Experimental-Z-Level",
  "FujiStruct",
  "more_buildings",
  "more_locations",
  "oa_additional_buildings_mod",
  "national_guard_camp",
  "realguns",
  "Medieval_Stuff",
  "bio_mod",
  "No_Acid_Zombies",
  "No_Fungi",
  "RL_Classes",
  "StatsThroughSkills",
  "filthy_morale",
  "safeautodoc",
  "more_classes_scenarios",
  "Arcana",
  "DinoMod",
  "Mining_Mod",
  "npc_traits",
  "blazemod",
  "boats",
  "deoxymod",
  "Tanks",
  "alt_map_key"
]

**Comment by chaosvolt** [comment]
Odd, let me grab the latest build to check.

**Comment by chaosvolt** [comment]
Okay yeah, weird. They were working on first implementation, but it looks like ALL spellcraft scrolls are broken, as well as the restored ritual blade. Trying to figure out if there's any stuff I might be missing here. Any ideas?

**Comment by chaosvolt** [comment]
AHAH! Found the issue.

```
    "id": "mutation_overgrowth",
    "type": "mutation_category",
    "category": "OVERGROWTH",
    "threshold_mut": "THRESH_OVERGROWTH",
```
```
    "id": "OVERGROWTH",
    "type": "mutation_category",
    "category": "OVERGROWTH",
    "threshold_mut": "THRESH_OVERGROWTH",
```

The first one used to work but now crashes, the second one seems to work. I could've sworn I tested spellcraft scrolls after fixing stuff caused by https://github.com/CleverRaven/Cataclysm-DDA/pull/24183 but that's the only thing I'd expect to cause this...

**Comment by Luckspeare** [comment]
Cool, thanks for the quick fix!  Great mod, thanks for maintaining it.

**Comment by chaosvolt** [comment]
Thank you. And it only took racking my brain for about 10 minutes trying to see what I did differently from vanilla mutations. And then accidentally not porting the changes into the test build and thus thinking that didn't fix it. Twice. ;~;
