### ISSUE TITLE
Error when recruiting the free merchants beside Hub 01 for sofia

### ISSUE THREAD

**Issue by miu135** [chaosvolt/cdda-arcana-mod#375]
I'm playing the march 11 version of DDA arcana and I don't know what's causing this but it seems like there are some terrains that are unable to be spawned.
Also seem like it's trying to upgrade the church with tacoma's people for some reason.

Error Log: 
[errorlogs.txt](https://github.com/chaosvolt/cdda-arcana-mod/files/13399264/errorlogs.txt)

**Comment by chaosvolt** [comment]
Hecc, will tackle this later today when I can.

**Comment by chaosvolt** [comment]
There we go, https://github.com/chaosvolt/cdda-arcana-mod/commit/9da71b064e644f367805a0d9e56b5c2ed6582d55 should fix it. Lemme know if I missed anything.

**Comment by miu135** [comment]
The error is resolved but now the furnitures inside the house still won't appear in map memory except for the workbenches and display racks.

- Pre-mission submission
Seen:

![bug1](https://github.com/chaosvolt/cdda-arcana-mod/assets/54433550/c04f9fb0-ae49-4df1-bbc3-3eba3204d1a0)

![bug2](https://github.com/chaosvolt/cdda-arcana-mod/assets/54433550/b46cc53f-3f85-41f1-8fa5-1e968c36e13b)

Unseen:

![bug3](https://github.com/chaosvolt/cdda-arcana-mod/assets/54433550/59775781-570a-4e50-8f95-d690f62e13d2)

- Post-mission submission
Seen:

![bug4](https://github.com/chaosvolt/cdda-arcana-mod/assets/54433550/57865b1e-7056-414b-a783-a5e9605684b7)

![bug5](https://github.com/chaosvolt/cdda-arcana-mod/assets/54433550/ce7692b9-ea48-4e5c-a369-f09abc88c543)

Unseen:

![bug6](https://github.com/chaosvolt/cdda-arcana-mod/assets/54433550/d3a23729-8606-40ec-8d41-0c7cafe0462c)

**Comment by chaosvolt** [comment]
If the furniture is actually physically there then that's a problem with map memory code, not something I can fix on my end.

**Comment by miu135** [comment]
> If the furniture is actually physically there then that's a problem with map memory code, not something I can fix on my end.

Is there anything I can do to fix it myself?

**Comment by chaosvolt** [comment]
Not sure if anything can be done aside from opening an issue over there and pointing out that mapgen updates can desync the map memory. If you can play around with the refugee center or ranch camp to find an instance of this triggering in vanilla than even better, since they'll likely close the issue if you come to them with a third-party mod as the first example (despite it being a map memory code thing).

**Comment by miu135** [comment]
I see then, since the issue is mostly resolved I might as well close this issue.
