### ISSUE TITLE
Veinreaver Does No Damage

### ISSUE THREAD

**Issue by victorfeight** [chaosvolt/cdda-arcana-mod#38]
Build: 7699 experimentals
Steps to reproduce: create new world with Arcana, spawn veinreaver and blood essence, activate runes and throw at an enemy
Bug: Veinreaver causes no damage.

My character hears an explosion and sees a giant puddle of blood formed, but there's no damage caused to enemies. Am I missing something with this item?

**Comment by chaosvolt** [comment]
Odd. I noticed recently that AEA_FIREBALL does very little damage, and changed it to work around that. Have you tested the hellfire staff and demon claw? What about vanilla matchbombs?

Might be a hardcode issue.
