### ISSUE TITLE
Crash on Character Creation due to Essence Material

### ISSUE THREAD

**Issue by Canada1844** [chaosvolt/cdda-arcana-mod#381]
#10
    (dbghelp: RtlUserThreadStart+0x2b@0x7ffd31f2485b[ntdll.dll+0x485b]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
Backtrace emission took 3 seconds.
(continued from above) ERROR : src/main_menu.cpp:986 [bool main_menu::new_character_tab()] Error: Json error: data/mods/Arcana/materials.json:1:2: missing mandatory member "bash_resist"

Modlist attached here.
![image_2023-11-27_223652900](https://github.com/chaosvolt/cdda-arcana-mod/assets/152243673/a5665ff0-c0c3-40d9-b097-cb411257556c)

**Comment by chaosvolt** [comment]
Bit belatedly: make sure you're using the correct version, i.e. 0.G release of Arcana with 0.G DDA, or current version of the Arcana folder in master branch in latest experimental version. Sounds like your issue is loading current Arcana with old stable DDA.

**Comment by chaosvolt** [comment]
Yep, works in `2023-12-16-1905`.
