### ISSUE TITLE
In overmap_special 4x4_microlab_arcana, terrain "microlab_rock_border" is invalid.

### ISSUE THREAD

**Issue by waveyl** [chaosvolt/cdda-arcana-mod#388]
See DDA#70520

item 'modular_m4_carbine' has no variant 'm4a1'
See DDA#69725 and related PRs

**Comment by chaosvolt** [comment]
hecc

**Comment by chaosvolt** [comment]
Okay I'm not seeing any mention of the latter error but working on the former.

**Comment by chaosvolt** [comment]
Found the other errors, look to be specific to Tankmod: Revived and one fix for Cata++ too.
