### ISSUE TITLE
Typo in NPC dialogue

### ISSUE THREAD

**Issue by UNOwenWasMe** [chaosvolt/cdda-arcana-mod#394]
Hello, while playing I spotted a typo in the NPC dialogue here (see screenshot).

It should be "than" instead of "then".

Of course typos are not gamebreaking, but they are ugly, so I think it's right to tell you 👍 

![Screenshot 2024-01-27 145312](https://github.com/chaosvolt/cdda-arcana-mod/assets/44485882/b6335ea4-7ff6-4c7c-90b1-5fdc3641f4dd)

**Comment by chaosvolt** [comment]
Nice, thanks for spotting that. I also see a typo in the previous line, easy fix.
