### ISSUE TITLE
Golden violin doesn't spawn

### ISSUE THREAD

**Issue by BorkBorkGoesTheCode** [chaosvolt/cdda-arcana-mod#4]
The golden violin isn't present in item_groups, so the essence recipe cannot be used.

**Comment by chaosvolt** [comment]
The recipe comment has prophesied it: I am saddragon. Will remove in a bit whenb I get back, unless it's PR'd by then.

**Comment by chaosvolt** [comment]
Did a double-check. It seems that golden violins can in fact spawn in music stores. From json\mapgen\musicstore.json:

````
 { "item": "violin_golden", "x": 21, "y": 8, "chance": 95 }
````

Weird, but just in case they later eat that chance due to being silly (plus it's likely not REALLY from Hell itself), I can remove it if you think it's a good idea.

**Comment by chaosvolt** [comment]
Removed in https://github.com/chaosvolt/cdda-arcana-mod/commit/978b76e7b5e929893a7f8d94f5f35d3e4cd05125 for now.

**Comment by BorkBorkGoesTheCode** [comment]
I like the violin recipe; since I couldn't find the violin listed in item_groups, I thought you might want to know so you could add it to magic item spawns.

**Comment by chaosvolt** [comment]
Ah right. I guess it can be retained if it'll still stay a spawn in music shops. Did seem worth it to rebalance components at least.
