### ISSUE TITLE
Some mutation/cell biology specific fields ported to enchantments.

### ISSUE THREAD

**Issue by waveyl** [chaosvolt/cdda-arcana-mod#411]
See DDA#72034 and #72106

**Comment by chaosvolt** [comment]
Uuuugh. I'll fix this tomorrow or when I can get time, last few days have been busy.

**Comment by chaosvolt** [comment]
Oh, https://github.com/chaosvolt/cdda-arcana-mod/pull/412 fixes this if I recall.

**Comment by chrsrns** [comment]
CDDA commit 9f08089 and Arcana commit d52e431 still produces errors regarding the mutations.

**Comment by chaosvolt** [comment]
Fucking auuuugh. Been busy with IRL a fair bit lately.

**Comment by chaosvolt** [comment]
Okay, that should do it. I'm gonna have to chuck a Cata++ fix at Noct too, possibly later today if stuff doesn't come up.

I also see @GuardianDll has a part three out already which...I dunno if I'll be able to find time to set aside a draft PR so I won't be blindsided by this or not but we'll see.

**Comment by GuardianDll** [comment]
yeah, it's not the end, i plan to port all single numerical fields from mutations and cbms to enchantments
sorry for caused issues

**Comment by chaosvolt** [comment]
No worries, just might be slow to update things since been juggling stuff.

**Comment by waveyl** [comment]
@chaosvolt #72173 merged
