### ISSUE TITLE
Scenario near civilization

### ISSUE THREAD

**Issue by mding9** [chaosvolt/cdda-arcana-mod#42]
I feel like there should be a scenario that starts you off in the basement of a house with a magic lab. It should come at the expense of a few points and the inability to use the stronger magic classes, made up for by a safe base to hone your skills and the ability to raid nearby buildings for supplies.

**Comment by mding9** [comment]
"It has been days since your mentor left with a strained expression, ordering you to stay in the lab at all costs, and you have heard the screams start, die out, and get supplanted with the moaning of the dead. You eventually work up the courage to find answers for yourself, but fear the worst."

**Comment by chaosvolt** [comment]
Hmm. Might be interesting actually. If I knew how to guarantee magic basements without adding more mandatory specials, but I do want to avoid increasing the mandatory special count when possible, and new start locations will vastly increase the odds that I'll need to do so. Cathedral basements, churches, and such might be good ones that are reasonably common though, maybe.

**Comment by mding9** [comment]
Maybe some cabins or hermit shacks can be replaced with magicians' huts.

**Comment by chaosvolt** [comment]
True, I was thinking of adding arcanist variants of cabins and such, but only as a random alternative to the vanilla ones. It wouldn't really count as "near civilization" though, as cabins and hermit shacks tend not o spawn near cities.

**Comment by chaosvolt** [comment]
I've made a breakthrough. Gonna test how `regional_overlay` works and thus be able to separate arcanist basements into their own om_terrain.
