### ISSUE TITLE
Hermit gives quest "Earn The Favor From Beyond" even when the player cannot complete it.

### ISSUE THREAD

**Issue by Dracque** [chaosvolt/cdda-arcana-mod#423]
**Steps to reproduce**
1. Create a character, cross Dragonblood threshold.
2. Start Hermit quest chain and complete "Retrieve The Cursed Blade" and "Restore The Ritual Blade".
3. Ask for next quest. The Hermit doesn't take into account that the player has crossed Dragonblood threshold.

**Additional context**
When going through the dialogue options after asking about the second task the Hermit will mention that the player bears the Sanguine Order's transformations when the option "What happened to this one?" is selected. The Hermit also mentions that the player "will not be able to make full use of the blade once it is restored".
Giving the restored ritual blade to the Hermit after accepting the third quest, talking to the Hermit again and choosing "It doesn't feel like it's working. What am I doing wrong?" does not mark the quest as failed or completed.

**Versions and configuration**
- OS: Windows
    - OS Version: 10.0.22631.3447 (23H2)
- Game Version: fba1da1 [64-bit]
- Graphics Version: Tiles
- LAPI Version: 2
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [bn],
    Cataclysm++ [Cata++],
    Arcana and Magic Items [Arcana],
    Arcana/Cata++ Patchmod [Arcana_Cata++_Patch],
    MST Extra [MST_Extra],
    Disable NPC Needs [no_npc_food],
    Limit Fungal Growth [limit_fungal_growth],
    Stats Through Kills [stats_through_kills],
    Faster Stamina Regen [stamina_regen_buff],
    No Rail Stations [No_Rail_Stations],
    Tankmod: Revived [Tankmod_Revived]
]

**Comment by chaosvolt** [comment]
Thanks, will look into the dialogue when I can. My rough guess is, the hermit has some dialogue conditions that check for failing due to having a threshold during the preamble for the final mission, but I forgot that a failure check during the preamble of the third mission would be required.

**Comment by chaosvolt** [comment]
Looking into this now finally, so far the dialogue conditions seem like they should be set up to catch this correctly, but gonna test it some more. I'm assuming that some dialogue path in here is letting you bypass the intended dialogue and ask him for a mission anyway, while the mention of the "it's not working" dialogue in the mission query I assume means that it's not correctly removing the active mission when rerouting the player to the "mission failed" dialogue (or it might even itself be breaking some things due to the line's response being `TALK_NONE` instead of `TALK_DONE`).

**Comment by chaosvolt** [comment]
There we go, https://github.com/chaosvolt/cdda-arcana-mod/commit/ea7d54b6ffe8e4eacc7fbb764d633fc5a1642c99 should close both loopholes, but do let me know if you find any other oddities.

**Comment by Dracque** [comment]
Tested the quest chain with two post threshold characters (Dragonblood and Prime).
When asking for the third quest hermit takes threshold into account and doesn't give it (no mission log update).

Issue appears to be entirely fixed.
