### ISSUE TITLE
json error: see cost uses invalid number format

### ISSUE THREAD

**Issue by JohnHenryEton** [chaosvolt/cdda-arcana-mod#438]
DEBUG    : Error: Json error: H:/Games/cdda/dda/userdata/mods/Arcana/overmap_and_mapgen/overmap_terrain.json:1:2: <color_white><color_cyan>In curious_structure: See cost uses invalid number format</color>

<color_light_red>[</color>
<color_cyan>▲▲▲</color>
  {
    "id": "curious_structure",
</color>

 FUNCTION : bool main_menu::load_game(const std::string&, const save_t&)
 FILE     : src/main_menu.cpp
 LINE     : 1103
 VERSION  : cdda-experimental-2024-08-07-0555 293f801

**Comment by Skully-Bojangles** [comment]
I was just about to report the same thing. Cata++ seems to have the same issue.

**Comment by chaosvolt** [comment]
Just now PR'd some fixes for Cata++ that includes that fix, will tackle this for Arcana next.

**Comment by JohnHenryEton** [comment]
now getting this

 DEBUG    : Error: Json error: H:/Games/cdda/dda/userdata/mods/Arcana/overmap_and_mapgen/overmap_terrain.json:9:16: <color_white><color_cyan>Expected number</color>

    "color": "i_light_red",
    "looks_like": "church",
<color_light_red>    "see_cost": "high",</color>
              <color_cyan>▲▲▲</color>
    "flags": [ "RISK_HIGH" ]
  },
</color>


 FUNCTION : new_character_tab
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\main_menu.cpp
 LINE     : 1051
 VERSION  : 09410b2

**Comment by JohnHenryEton** [comment]
Scratch previous comment, tested wrong version I believe
