### ISSUE TITLE
JSON Error

### ISSUE THREAD

**Issue by Vomgnar** [chaosvolt/cdda-arcana-mod#440]
Hi Chaosvolt!

Found a minor bug in Arcana_BN/items/tools.json
Just 2 missing commas.  My apologies if this is already fixed and I missed it.  Love your work! thanks!

"id": "bot_mech_arcana",
"type": "TOOL",
	.
	.
"flags": [ "ALLOWS_REMOTE_USE" ]<---
"use_action": {
_______________________________________________________________	
id": "transmutation_crucible",
type": "TOOL",
	.
	.
"flags": [ "ALLOWS_REMOTE_USE" ]<---
"use_action": { "type": "deploy_furn", "furn_type": "f_transmutation_crucible_deployed" }

**Comment by chaosvolt** [comment]
Whoops, thanks for spotting that!
