### ISSUE TITLE
unable to create a character when Arcana is included in a worlds mods

### ISSUE THREAD

**Issue by GreyMouser69** [chaosvolt/cdda-arcana-mod#441]
Attempting to create a character crashes with the following error:

 DEBUG    : Error: Json error: data/mods/Arcana/materials.json:1:2: missing mandatory member "bash_resist"

[
 ^
  {
    "type": "material",
    "id": "essencemat",

 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 986
 VERSION  : d6ec466

**Comment by chaosvolt** [comment]
Make sure you're actually using the current version of Arcana if you're using latest experimental, not any of the stable releases. It's literally right in the release name what version it's for.
