### ISSUE TITLE
Yet another obsoletion in DDA

### ISSUE THREAD

**Issue by waveyl** [chaosvolt/cdda-arcana-mod#442]
See DDA#75865 and #75925

**Comment by Tranberry** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/pull/75925
https://github.com/CleverRaven/Cataclysm-DDA/pull/75865

for easier navigation.

**Comment by chaosvolt** [comment]
Pain. Will work on it later today when I get the chance, hecc.

**Comment by chaosvolt** [comment]
Finally looking into this, I only see a quick fix involving atomic batteries that needs fixing it seems, don't see any problems with the magazine spawn stuff far as I can see.
