### ISSUE TITLE
Monster from nether faction

### ISSUE THREAD

**Issue by Tiareth** [chaosvolt/cdda-arcana-mod#449]
During one of the starts I came across a veiled butterfly. It and several other monsters are part of the Nether faction (and probably the supported MoM mod, but judging by the fact that I found them in Hitchhiker's Guide to the Cataclysm, this butterfly and some other monsters are part of the main game). In theory, they should drop otherworldly resources, but as far as I understood from a quick look at the files, there are none in Arcana(throught git search i searched for butterfly and eldritch stomper). In theory, I could probably either modify Arcana itself or even create a full-fledged patchmod for compatibility with MoM on my own(and then possibly XEDRA), but digging through the files I will inevitably get too many spoilers. Therefore, I kindly ask you to add drop/compatibility at least to those monsters that are in core files of game.

**Comment by chaosvolt** [comment]
I'd need to probably add a patchmod for that mod it seems. I'll have to work on it when I can, been busy a lot lately ^^"

**Comment by Lorindel** [comment]
Is it possible to update the mod and remove patchmods without ending current playthrough?

**Comment by Lorindel** [comment]
Ah, newermind i am died, go to the shrine, kill some dudes inside and was killed by swarm of spiders nearby.
