### ISSUE TITLE
Adding weapon in practice recipes and change weapon categories. (i did it)

### ISSUE THREAD

**Issue by Tiareth** [chaosvolt/cdda-arcana-mod#452]
I don't know how to do it properly, so I'll do it this way.
All started when level up my bashing to second level and I was unable to practice great hammer's proficiency using the hammer of the hunter that essentially echanted version of ususal hammer. Hammer+1 do, but not HotH. I try to fix it. I dive in code(god bless git's author it's so comfortable to ctrlf all files at once) of magiclism to learn and do the same. Also i decide try to fix medieval_swords error. I found that weapon categories was changed. https://github.com/CleverRaven/Cataclysm-DDA/pull/68582  So i changed all weapons in tool.json
[tools.json](https://github.com/user-attachments/files/17542432/tools.json)
[recipe_practice_requirements.json](https://github.com/user-attachments/files/17542437/recipe_practice_requirements.json)
Please check my changes and correct if necessary, because I only worked with tools.json, so if the Arcana adds another weapon with which you can practice and/or which has categories that were affected by the changes in the main game, then I did not touch them, because I did not know. And I still do not want to actively dig into all the files (I'm still afraid of spoilers).

**Comment by chaosvolt** [comment]
Hecc, if I get the chance to will work on it later today I guess. Been busy a lot with IRL stuff lately. ^^"

**Comment by Tiareth** [comment]
One of the reasons why I did it myself. Last time you wrote that you were busy, and it is also clear that you like BN much more, and for some reason you are not in the DDA discords.

**Comment by chaosvolt** [comment]
I mean, that still means I need to find time to add them to a commit and double-check they work but this does make it easier, true. And honestly yes, I moved from DDA to BN quite some time ago, keep in mind I haven't been a contributor to DDA since early 2016: https://github.com/CleverRaven/Cataclysm-DDA/pull/15203

**Comment by chaosvolt** [comment]
Was easy enough to test since wasn't too busy this morning. Thank you for this.

**Comment by chaosvolt** [comment]
Forgot to add to https://github.com/chaosvolt/cdda-arcana-mod/commit/83b72540f6c4bb68241145ad69524a63e739edf4 a note to auto-close this. :D
