### ISSUE TITLE
Fires not producing by-products as in vanilla

### ISSUE THREAD

**Issue by OhDC** [chaosvolt/cdda-arcana-mod#49]
Noticed a minor issue today after trying out this mod.

Any fire source in vanilla will produce by-products dependant on material used, eg; two-by-fours produce Wood Ash.

With only this mod added to the game this effect no longer happens.

I found this: https://github.com/CleverRaven/Cataclysm-DDA/pull/23600 that I believe relates to said effect in vanilla.

**Comment by chaosvolt** [comment]
That PR is several months old and, if there's anything breaking it, it definitely isn't a mod doing it. HOW, when this is a JSON mod and ash is a hardcoded thing?

**Comment by chaosvolt** [comment]
Oh. That...makes sense now. I see what caused this, and I'm now wondering what in the flying fuck possessed me to do the bit of JSON that's responsible. I can only assume copy-from did work, though who knows...
