### ISSUE TITLE
Arcana Russian localization

### ISSUE THREAD

**Issue by Adevald** [chaosvolt/cdda-arcana-mod#54]
There is some suggestion from me. I have plan to localize this mod on russian lang, but dont know how to synchronize it from future updating. I'll handle all translition works, but maybe you give me a cue how to di that?

**Comment by chaosvolt** [comment]
Unfortunately I have no experience with how CDDA handles localization or how it deals with mods, so I'm not sure what the best approach would be.

**Comment by Adevald** [comment]
> Unfortunately I have no experience with how CDDA handles localization or how it deals with mods, so I'm not sure what the best approach would be.

Oh. Okay. But if i can understand and deal it by myself, could you merge it to original mod?

**Comment by chaosvolt** [comment]
Oh? Sure? No idea how this works but if it's doable sure.

**Comment by Adevald** [comment]
@chaosvolt im seek a way to make operational translition more easy, but could you help me in that? Maybe maybe it makes sense to create here additional branch only for Russian translition. I'll time to time compare master to rus_branch, and update rus_branch with new content and fix. Is it possible?

**Comment by chaosvolt** [comment]
That'd be a massive pain in the ass to keep up-to-date, but if that's the only way to do so then might have to. Sorry that I haven't done much lately, as I've been rather busy juggling a lot of things lately.

**Comment by Adevald** [comment]
@chaosvolt Thanks for cooperation. I don't think its your duty, so relax and do things when you want to do.
