### ISSUE TITLE
base game removed 'obsolete' mushrooms

### ISSUE THREAD

**Issue by adamkad1** [chaosvolt/cdda-arcana-mod#57]
game throws a noncrashing error when loading, saying magic and poison mushrooms are invalid, your gonna need to fix up the recipe for migo summoning
https://github.com/CleverRaven/Cataclysm-DDA/commit/3f076f8a35f4719f5186aee28c340399d3da43ab

**Comment by chaosvolt** [comment]
Whoops. Thank you for that, got caught up in a lot of stuff lately so I ended up forgetting that.
