### ISSUE TITLE
Arcana

### ISSUE THREAD

**Issue by Axema** [chaosvolt/cdda-arcana-mod#58]
I was wondering if you could allow me to mix up this mod with [mine](https://github.com/Axema/Vampiric-Stuff)? I was thinking of the same idea with the winning cdda mod, and my plan focuses on adding your contents as the source of quests. Your words are appreciated about it :smiley:

If you agree, just comment and close this issue :slightly_smiling_face:

**PS**: Damn, I love your style when it come to dialogues ^_^

**Comment by chaosvolt** [comment]
Oh, hmm. Looks like it'd be interesting. The thing I'd recommend, as with Ascension, is that maintaining a separate competing copy of Arcana alongside it will make keeping your mod up-to-date harder, so making it simply require arcana as a dependency and going from there probably will be easier in the long run.

Of course, if there's anything in particular that you'd need Arcana to do for your ideas to work right, feel free to tell me and I'll try and see what'd be needed on either end to make it work.

Thank you, in any case. Hope it goes well. :3

**Comment by Axema** [comment]
Oh, okay. I am thinking of combining Vampiric stuff and Arcana into one like this:

Vampiric Stuff => Mod <= Arcana

Wherein 'Mod' is our extension mod with both dependencies of two mods.
(sorry, I can't explain it clearly)

Also, I thank you for your permission :slightly_smiling_face:
