### ISSUE TITLE
Missing separator in monsters.json, fix included

### ISSUE THREAD

**Issue by jmattspartacus** [chaosvolt/cdda-arcana-mod#59]
Went to launch with the latest build, got this error, I put a fix at the bottom
` DEBUG    : Error: data/mods//cdda-arcana-mod-master/Arcana/monsters.json: line 698:34: missing separator

    "death_drops": {  },
    "special_attacks": [ [ "RANGED_PULL", 20 ], [ "LUNGE", 10 ] ],
    "extend": { "flags": [ "SEES"
                                 ^
                                  "REVIVES" ] },
    "delete": { "flags": [ "BASHES", "GROUP_BASH", "ATTACKMON" ] }
  },

 
 FUNCTION : bool main_menu::load_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 942 `

Fixed by replacing the definition starting at line 698 with (really only adds a comma to the array)
`
  {
    "id": "mon_thing_summoned",
    "copy-from": "mon_thing",
    "type": "MONSTER",
    "name": "summoned thing",
    "death_drops": {  },
    "special_attacks": [ [ "RANGED_PULL", 20 ], [ "LUNGE", 10 ] ],
    "extend": { "flags": [ "SEES", "REVIVES" ] },
    "delete": { "flags": [ "BASHES", "GROUP_BASH", "ATTACKMON" ] }
  },`

**Comment by chaosvolt** [comment]
Ack, sorry about that. That's what happens when you rush through finalizing something you've been fiddling with all day...
