### ISSUE TITLE
getting an error in newest experimental build

### ISSUE THREAD

**Issue by hexob** [chaosvolt/cdda-arcana-mod#69]
here is the error

https://imgur.com/a/lXeOQAL

i get the error on build 9089

**Comment by hexob** [comment]
i think this is whats causing it 

https://github.com/CleverRaven/Cataclysm-DDA/commit/5557a8c732c554f2dfd222b87d6f94630fe00deb

**Comment by chaosvolt** [comment]
Hnng, I see the likely cause yeah. Thanks.

**Comment by chaosvolt** [comment]
There we go. Tell me if anything else comes up, and thank you.

**Comment by TheWalrusFighter** [comment]
I'm still getting this error on 9095. am i missing something? do i have to update the mod manually?

**Comment by chaosvolt** [comment]
Yes. You always have to update your mods manually. The launcher does not do anything automatically last I checked.
