### ISSUE TITLE
Mantle of shadows dissappearing when running out of charges

### ISSUE THREAD

**Issue by Ignaramico** [chaosvolt/cdda-arcana-mod#71]
I dont know if its intended or not (in case it is, sorry for the issue).

The mantle of shadows dissapears while using it at the moment it runs out of charges, it shows the default message of turning it off on the log window.

**Comment by chaosvolt** [comment]
Huh, that's weird. Let me see if some weirdness is going on with item reversion...

**Comment by chaosvolt** [comment]
Yep, mantle of shadows was missing `revert_to` for some reason. Sorry about that, and thank you for finding that.

**Comment by Ignaramico** [comment]
Glad to help (n.n)/
