### ISSUE TITLE
Suggestion: Dragonblood mutation tree

### ISSUE THREAD

**Issue by adamkad1** [chaosvolt/cdda-arcana-mod#76]
With the new magic system, dragonblood should have some way to compensate for all the encumberance given by mutations, since they impair spellcasting rather heavily (it doesnt scream 'power' to me when you need to use 99% of your limb health to cast something like infernal flame)

**Comment by chaosvolt** [comment]
The forced mutation encumberance, later on, doesn't add up to much added penalty, though I will want to double-check the math on it. By far the biggest cause of the spell failure rate comes from spell level plus the fact that the hardcode uses Spellcraft skill to determine the rate, which is only formally defined as a skill you can level up in Magiclysm (the fact the hardcode can be set to draw from a non-existent skill without causing an error is wizardry to me).

@KorGenT has mentioned that unhooking spells from a specific skill, allowing you to set what skill a spell uses, is a known entry on his to-do list (which exceeds even my pile of ideas in length by a wide margin), so eventually Arcana spells will draw upon arcana skill to determine failure rate, and that'll make things way easier given getting Dragonblood spells at all requires something you craft with mid-level arcana skill.

Side note, last I checked spells only consume their cost on success, not failure...
