### ISSUE TITLE
New skill catagory sorting system in mainline causing arcana to stop working.

### ISSUE THREAD

**Issue by zakhad** [chaosvolt/cdda-arcana-mod#77]
I believe to the best of my knowledge this recent changed has caused a few mods such as arcana to be unusable without adding a display catagory from the following commit that got mainlined 

https://github.com/CleverRaven/Cataclysm-DDA/pull/33590
 
I applied the same change that was suggested for magiclysm as arcana was having the same issue.
 
https://github.com/CleverRaven/Cataclysm-DDA/issues/33693

"display_category": "display_ranged", is needed in the arcana.json

`[
  {
    "type": "material",
    "ident": "essencemat",
    "name": "Magical Essence",
    "density": 1,
    "bash_resist": 20,
    "cut_resist": 20,
    "acid_resist": 99,
    "fire_resist": 99,
    "elec_resist": 99,
    "chip_resist": 99,
    "dmg_adj": [ "lightly damaged", "damaged", "very damaged", "thoroughly damaged" ],
    "bash_dmg_verb": "damaged",
    "cut_dmg_verb": "damaged"
  },
  {
    "type": "skill",
    "ident": "magic",
    "name": "arcana",
    "display_category": "display_ranged",
    "description": "Your knowledge of strange, anomalous powers from far-off worlds.  While certain artifacts are beyond mortal understanding, this skill can be used for creating and using a few odd devices, some with lethal applications.",
    "tags": [ "combat_skill" ]
  }
]`

which seemed to have fixed the issue.

The issue in question was.

` DEBUG    : Error: data/mods//Arcana/arcana.json: line 17:3: member not found: display_category

    "cut_dmg_verb": "damaged"
  },
  {
  ^

    "type": "skill",
    "ident": "magic",

 
 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 815`

**Comment by chaosvolt** [comment]
Oof, one sec...

**Comment by chaosvolt** [comment]
Not sure which category is best honestly, I guess ranged since some magic weapons use it, but it also affects crafting and interaction stuff...

**Comment by zakhad** [comment]
Guy wins the award for fastest issue response & resolution time of 2019! 10/10 would issue again.... wait what did i sign up for.... xD

Yeah i wasn't sure what category was best, it was just to make the issue known is all :)

**Comment by chaosvolt** [comment]
Just good luck that I happened to be messing around with part 2 of the spell conversion PR stuff at around the same time.

I went with interaction for now, but we'll see what sounds better in the future. I can even define custom display categories it seems, but will likely only bother with that if Magiclysm ends up imitating that.
