### ISSUE TITLE
Cursed Blade generates infinite blood essence

### ISSUE THREAD

**Issue by Highmongrel** [chaosvolt/cdda-arcana-mod#80]
When you fill and activate a cursed blade with blood essence, it's blood essence count goes up to 1200 and it's cap goes to 7200. At any point after that while it still has charge you can unload it, even when you just activate it.

This means you can infinitly trade 9 BE for 1200 BE every few seconds.

**Comment by chaosvolt** [comment]
Whoops. I'm guessing it was likely from whenever I had to set it to use blood essence instead of generic null ammo (which normally can't be reloaded or unloaded), for whatever bug I was trying to fix. Thanks for spotting that!
