### ISSUE TITLE
Text not wrapped on spell interface

### ISSUE THREAD

**Issue by Ignaramico** [chaosvolt/cdda-arcana-mod#83]
https://github.com/KorGgenT/Cataclysm-DDA/issues/81

Since your mod is kind of the main reason for this issue

**Comment by chaosvolt** [comment]
Shit, guessing that's due to name length. I'll have to see if I can implement that text color idea Korg suggested a while back instead?

**Comment by chaosvolt** [comment]
Should now be fixed by https://github.com/chaosvolt/cdda-arcana-mod/commit/84773b85d8b9ae59aff4174f7b6ff67eebac3a93, tell me if anything else comes up.
