### ISSUE TITLE
Spells missing information

### ISSUE THREAD

**Issue by Ignaramico** [chaosvolt/cdda-arcana-mod#84]
# Describe the bug
For what i seen, there are two spells that are missing information on the interface (radius and duration) they are the spells wall of force and consecrate

# Steps To Reproduce

1. reach the level to learn consecrate or wall force
2. highlight them
3. check the info side of the gui an notice the lack the information

# Screenshots
![Screenshot_2](https://user-images.githubusercontent.com/34730575/65391137-50c60e00-dd2b-11e9-9a30-82c101a8a0bd.jpg)

# Additional context

I dont think is related to issue #83, since other spells does show the necessary info, although messed up

**Comment by chaosvolt** [comment]
Yeah, I'll double-check those after I find out whether text color works for spell names.

**Comment by chaosvolt** [comment]
Other than that, not sure what else might be causing that...

**Comment by chaosvolt** [comment]
Found the common thread here: Overgrowth, Consecrate, and Wall of Force are all affected, it seems that AoE is not display for spells if their PRIMARY effect is ter_furn_transform
