### ISSUE TITLE
suggesting wall force spell revision

### ISSUE THREAD

**Issue by Ignaramico** [chaosvolt/cdda-arcana-mod#86]
after wall force got nerfed, only one wall does appear, making the information misleading
![Screenshot_1](https://user-images.githubusercontent.com/34730575/65469735-11341a80-de2e-11e9-9c84-66cabceafd61.jpg)
As you see the spell marks a 3 radius effect (and the aiming grid does indeed appear as a 3x3 radius square)
but the actual effect only spawns one block
![Screenshot_2](https://user-images.githubusercontent.com/34730575/65469779-46406d00-de2e-11e9-92f8-1915631e74a7.jpg)
thought it was because of the terrain (grass/dirt/pavement) but no.

So either, the info needs an update or there is mishap

**Comment by chaosvolt** [comment]
Whoops. It starts off as only 1 tile then expands, most likely the dummy `target_attack` I added so it grabs AoE was based off the pre-nerf value. Sorry about that.

**Comment by chaosvolt** [comment]
Er...wait...that's odd, it's got the AoE already synced, you sure?

**Comment by chaosvolt** [comment]
Added something that might fix it, about to give it a more thorough test.

**Comment by chaosvolt** [comment]
Okay yeah, this is messing with me a bit, Consecrate and Wave of Destruction seem to work, I don't get why Wall of Force is acting up...

**Comment by chaosvolt** [comment]
Ahah! I've found what seems to be the issue. For whatever reason, it's limiting the AoE of `ter_transform` spells to the minimum AoE, ignoring any increment towards maximum. You can actually see this with Overgrowth and Consecrate too, plus Wave of Destruction's mockup of AEA_PULSE.

I then tested debugging all spells and casting the effect directly, it seems that if the ter_transform is the PRIMARY spell the AoE will work, but any attempt to use AoE ter_transform as an extra effect will fail.

Pinging @korggent as this sadly is a code thing I really can't do much about. I can remove my workaround for AoE not displaying in spell preview for Consecrate, Overgrowth, and Wall of Force, but this is going to be an unavoidable issue for Infernal Flame and Wave of Destruction.

**Comment by chaosvolt** [comment]
Closing as I've since undone the workaround that caused the exact issue of the OP, but I've found some bigger problems with subspell AoE that go beyond last night's comment, reported in https://github.com/KorGgenT/Cataclysm-DDA/issues/83
